usgs/earthquake-eventpages

src/htdocs/modules/summary/0-0-1/js/InteractiveMap.js

Added base layers to interactive map using ArcGIS urls.

added baselayers to interactive map.

---

src/lib/inc/html.inc.php

Spelled out shakemap in eventpage quicksumary.

changed abbr of SM to Shakemap

---

src/htdocs/modules/base/0-0-1/js/Attribution.js
src/htdocs/modules/base/0-0-1/js/EventModulePage.js
src/htdocs/modules/summary/0-0-1/css/index.scss
src/htdocs/modules/summary/0-0-1/js/SummaryPage.js

So far, link contributor name in footer.
More to come

Latesteq 289

---

src/htdocs/terms.php

added missing technical terms

---

src/htdocs/terms.php

added moment tensors description

Latesteq 286

---

src/htdocs/modules/impact/0-0-1/css/_DYFIFormPage.scss
src/htdocs/modules/impact/0-0-1/js/DYFIFormPage.js

Add ciim_report field
Update styles for successful submission.

Updates to DYFI Form

---

src/htdocs/css/_event-header.scss

Update padding, the problem exists when verdana is used as the font for the .roman class

Update impact bubbles so that Yellow pager text fits inside

---

Gruntfile.js
src/htdocs/js/unknown.js
src/lib/pre-install.php

Fixes for unknown event page build process.

Update unknown event

---

src/htdocs/modules/summary/SummaryPage.js

Update logic that selects nearby-cities product to use the most recent product that matches the eventsource and eventsourcecode.

LATESTEQ-292

---

src/htdocs/css/_MousePosition.scss
src/htdocs/css/index.scss
src/htdocs/js/map/MousePosition.js
src/htdocs/modules/summary/InteractiveMap.js
src/htdocs/modules/summary/_InteractiveMap.scss

Util.isMobile() doesn't seem to work in the chrome debugger.   Not certain how to test.   
Used .summary-interactive-map for the css to override leaflet.   Might want to add a specific container for this, so the code is more reusable.

Latesteq 302

---

src/htdocs/modules/scientific/MomentTensorPage.js
src/htdocs/modules/scientific/_FiniteFaultPage.scss
src/htdocs/modules/scientific/_FocalMechanismPage.scss
src/htdocs/modules/scientific/_MomentTensorPage.scss

This is for the scientific summary styles

Update styles to be more consistent across the different products.

---

src/htdocs/modules/summary/_DYFIUTMLayer.scss

that way it won't conflict with dyfi-summary styles on the summary pages

Scope dyfi-summary in pop-up on interactive map

---

src/htdocs/modules/summary/SummaryPage.js
test/spec/modules/summary/SummaryPageTest.js

- Loops over all products of given type instead of repeatedly showing first product.
- Only add header if title is non-null.

Summary Fixes

---

src/htdocs/modules/base/SummaryDetailsPage.js
src/htdocs/modules/impact/DYFIPage.js
src/htdocs/modules/impact/PagerPage.js
src/htdocs/modules/impact/ShakeMapPage.js
src/htdocs/modules/impact/_PagerPage.scss
src/htdocs/modules/scientific/FiniteFaultPage.js
src/htdocs/modules/scientific/HypocenterPage.js
src/htdocs/modules/scientific/MomentTensorPage.js

Update getDetailsContent to return DOM elements. This is required before https://github.com/usgs/earthquake-eventadmin/pull/11

LATESTEQ-330

---

src/htdocs/modules/summary/_TectonicSummary.scss

Add css to display image for new tectonic summary region near alaska

Tectonic Summary Update

---

src/htdocs/modules/summary/ShakeMapStationLayer.js

Also shows intensity as circles.
event that shows this.   us20002926

Intensity is also shown as circles

---

package.json
src/htdocs/modules/impact/DYFIFormPage.js

Update the expiration date on the DYFI form

Omb update

---

src/htdocs/terms.php

Fix Typo.
https://my.usgs.gov/jira/browse/LATESTEQ-362

LATESTEQ-362

---

src/htdocs/modules/base/EventPage.js
src/htdocs/modules/summary/InteractiveMap.js

Fixes an issue with the cache not working properly in IE11.

Ie11 Hotfix

---

src/htdocs/terms.php

Fixed typo under Review status section

fixed typo

---

src/htdocs/modules/scientific/tensor/Tensor.js

Fixes usgs/earthquake-eventpages#210

Add mapping for UU moment tensor methodID

---

src/htdocs/css/_event-header.scss

Reduce margin between impact bubbles and page title

---

src/htdocs/modules/summary/SummaryModule.js

Changed Google Earth KML to Download KML

---

src/htdocs/modules/impact/DYFIPage.js

fixes usgs/earthquake-eventpages#216
- Used better wording for buttons

Changed responses to Locations

---

src/htdocs/css/_responsiveTableScientific.scss
src/htdocs/modules/impact/ShakeMapPage.js
src/htdocs/modules/impact/_ShakeMapPage.scss
src/htdocs/modules/scientific/_HypocenterPage.scss

Update station list styles

---

src/htdocs/modules/base/ImpactUtil.js

Added ndash as the default to translateMmi instead of the empty string

---

src/htdocs/modules/base/Attribution.js

changed www.scsn.org to www.cisn.org

---

gruntconfig/browserify.js
src/htdocs/js/core/EventPage.js
src/htdocs/js/core/Module.js
src/htdocs/js/general/GeneralSummaryModule.js
src/htdocs/js/general/LocationView.js
src/htdocs/js/shakemap/ShakeMapModule.js
test/spec/core/EventPageTest.js
test/test.js

Also updates ShakeMapModule to use TYPES property instead of hasContent method.

Update EventPage moduleHasContent to support scenarioMode option

---

etc/products/dyfi/us10004u1y/us/1457013501095/cdi_zip.xml
example/_navigation.inc.php
example/dyfi/DYFIResponsesViewExample.js
example/dyfi/DYFIResponsesViewExample.php
example/example.php
gruntconfig/browserify.js
src/htdocs/css/dyfi/_DYFIResponsesView.scss
src/htdocs/css/event.scss
src/htdocs/js/dyfi/DYFIResponsesView.js
test/spec/dyfi/DYFIResponsesViewTest.js
test/test.js

Create DYFIResponsesView fixes #336

Create DYFI ResponseView #336

---

example/general/NearbyPlacesViewExample.js
src/htdocs/js/general/NearbyPlacesView.js

fixes usgs/earthquake-eventpages#341

Usgs/earthquake eventpages#341

---

example/_navigation.inc.php
example/general/GeoserveNearbyPlacesViewExample.js
example/general/GeoserveNearbyPlacesViewExample.php
gruntconfig/browserify.js
src/htdocs/js/core/Formatter.js
src/htdocs/js/general/GeneralSummaryModule.js
src/htdocs/js/general/GeoserveNearbyPlacesView.js
test/spec/core/FormatterTest.js
test/spec/general/GeoserveNearbyPlacesViewTest.js
test/test.js

fixes usgs/earthquake-eventpages#301

Usgs/earthquake eventpages#301

---

src/htdocs/js/dyfi/DYFIResponsesView.js

Create DYFIResponsesView corrected review comments.

---

src/htdocs/js/shakemap/ShakeMapView.js

Update ShakeMapView with comments from PR

---

src/htdocs/js/dyfi/DYFIResponsesView.js

Modifications per pull request

---

src/htdocs/js/dyfi/DYFIIntensityGraphView.js
test/spec/dyfi/DYFIIntensityGraphViewTest.js

This addresses comments/ fixes #334

Destroy the graph and all sub views

---

src/htdocs/js/shakemap/ShakeMapView.js

Addresses comments/ fixes #294

Update ShakeMapView to destroy the tablist and shakemap station list

---

src/htdocs/js/core/EventPage.js
src/htdocs/js/moment-tensor/MomentTensorModule.js
test/spec/moment-tensor/MomentTensorModuleTest.js
test/test.js

fixes usgs/earthquake-eventpages#322

Implement moment tensor module and tests

---

src/htdocs/js/finitefault/FiniteFaultModule.js
test/spec/finitefault/FiniteFaultModuleTest.js

addresses comments and fixes #329

Update FiniteFaultModule based on comments

---

src/htdocs/js/core/Module.js

fixes usgs/earthquake-eventpages#282
- Changed text

Usgs/earthquake eventpages#282

---

src/htdocs/js/pdl/CatalogEvent.js
test/spec/pdl/CatalogEventTest.js
test/test.js

Fixes usgs/earthquake-eventpages#291

Catalog event tests

---

gruntconfig/browserify.js
src/htdocs/css/event.scss
src/htdocs/css/general/_GeneralSummary.scss
src/htdocs/css/general/_LocationMap.scss
src/htdocs/js/core/AccordionView.js
src/htdocs/js/core/LinkProductView.js
src/htdocs/js/core/Module.js
src/htdocs/js/core/TextProductView.js
src/htdocs/js/general/GeneralSummaryModule.js
src/htdocs/js/general/GeoserveRegionSummaryView.js
src/htdocs/js/general/LocationView.js
src/htdocs/js/map/InteractiveMapView.js
test/spec/core/AccordionViewTest.js
test/spec/core/LinkProductViewTest.js
test/spec/general/GeoserveRegionSummaryViewTest.js
test/test.js

Fixes usgs/earthquake-eventpages#308
Initial implementation, could use more tests.

General module

---

gruntconfig/browserify.js
src/htdocs/js/core/EventPage.js
src/htdocs/js/waveform/WaveformModule.js
test/spec/waveform/WaveformModuleTest.js
test/test.js

fixes usgs/earthquake-eventpages#328

Usgs/earthquake eventpages#328

---

src/conf/config.inc.php
src/htdocs/index.php
src/htdocs/js/core/EventPage.js
src/htdocs/js/core/Module.js
src/htdocs/js/dyfi/DYFIFormModule.js
src/lib/configure.inc.php
test/spec/core/EventPageTest.js

Add INSTALLATION_TYPE pre-install option (296)

---

src/htdocs/css/general/_GeneralSummary.scss
src/htdocs/css/general/_LocationMap.scss
src/htdocs/js/general/GeneralSummaryModule.js
test/spec/general/GeneralSummaryModuleTest.js
test/test.js

Fixes #308 
us20002l0w is an example event with a general-header product.

General module 2

---

src/htdocs/css/_event-header.scss
src/htdocs/js/core/EventPage.js

Add quick summary bubbles to event page header

---

src/htdocs/js/shakemap/ShakeMapView.js

Finish up some outstanding TODO comments on ShakeMapView.
Event us20005cx1 on dev has info.json for testing.

ShakeMap TODOs

---

src/htdocs/js/finite-fault/FiniteFaultModule.js
src/htdocs/js/focal-mechanism/FocalMechanismModule.js
src/htdocs/js/impact/ImpactSummaryModule.js
src/htdocs/js/origin/OriginModule.js
src/htdocs/js/scientific/ScientificSummaryModule.js

Update Cross Module Links (415)

---

src/htdocs/js/waveform/WaveformModule.js

fixes usgs/earthquake-eventpages#417

Usgs/earthquake eventpages#417

---

src/htdocs/js/core/EventPage.js

Added Download KML, and Latest Earthquakes links (400)

---

src/htdocs/js/core/EventPage.js

fixes usgs/earthquake-eventpages#339
- Added redirects

added redirects

---

src/htdocs/css/core/_Module.scss

Make current module highlight in left nave (416)

---

src/htdocs/js/dyfi/DYFIView.js

Turn off shakemap, turn on DYFI on interactive map. (428)

---

src/htdocs/js/pdl/Content.js

fixes usgs/earthquake-eventpages#433
- Removed TODO comment

removed TODO comment

---

src/htdocs/js/core/ProductView.js

ProductView TODO (425)

---

src/htdocs/js/core/EventPage.js

fixes usgs/earthquake-eventpages#446
- Updated text for comcat link and scenarios link.
- Updated link to technical terms.

Usgs/earthquake eventpages#446

---

src/htdocs/css/core/_TextProductView.scss

This was for the impact-text on the ImpactSummaryModule
fixes #451

Add margin-top to all text products

---

src/htdocs/js/impact/ImpactSummaryModule.js

Remove title from Impact Summary

---

src/htdocs/js/general/GeneralSummaryModule.js
src/htdocs/js/map/InteractiveMapModule.js

fixes usgs/earthquake-eventpages#449
- Changed general summary module title.

updated general summary module title

---

src/htdocs/js/focal-mechanism/FocalMechanismModule.js
src/htdocs/js/focal-mechanism/FocalMechanismView.js
src/htdocs/js/moment-tensor/MomentTensorModule.js
src/htdocs/js/origin/OriginModule.js

Move/Add title to Origin, Moment Tensor, and Focal Mechanism pages

---

src/htdocs/js/impact/ImpactSummaryModule.js

Clear the header before appending

---

src/htdocs/css/dyfi/_DYFIFormView.scss
src/htdocs/js/dyfi/DYFIFormView.js

Increase size of Felt Report header. Position OMB number in top-right corner of form

---

src/htdocs/js/focal-mechanism/FocalMechanismModule.js
src/htdocs/js/focal-mechanism/FocalMechanismView.js
src/htdocs/js/moment-tensor/MomentTensorModule.js
src/htdocs/js/origin/OriginModule.js

Module titles

---

src/htdocs/js/core/EventPage.js
src/htdocs/js/event.js
src/htdocs/js/pdl/CatalogEvent.js
src/htdocs/unknown.php

Updated unknown.php and dependent resources in order for the unknown form to work again.

Unknown Form

---

src/htdocs/js/core/Attribution.js

Attribution todos

---

src/htdocs/js/dyfi/DYFIFormView.js

Call classList.add() for each class name, fixes IE bug

---

gruntconfig/browserify.js
src/htdocs/js/core/CooperatorLogo.js
src/htdocs/js/core/EventPage.js

Add cooperator logo for the preferred origin to the site banner

---

src/htdocs/js/core/EventPage.js

Create onAttributionReady method that handles loading attribution data

---

src/htdocs/js/dyfi/TextQuestionView.js

Fixed Null in Comment for IE

---

src/htdocs/css/core/_Module.scss
src/htdocs/css/dyfi/_DYFIIntensityGraphView.scss
src/htdocs/css/dyfi/_DYFIView.scss
src/htdocs/css/event.scss
src/htdocs/css/shakemap/_ShakeMapStationList.scss
src/htdocs/js/dyfi/DYFIIntensityGraphView.js
src/htdocs/js/dyfi/DYFIView.js
src/htdocs/js/losspager/PAGERView.js
src/htdocs/js/shakemap/ShakeMapView.js

fixes #489
fixes:
- masking of horizontal scrolling shadow on scientific summary tables
- tables breaking out of the template grid (PAGERView)
- Spacing issues

Usgs/earthquake eventpages#489

---

src/htdocs/js/core/Module.js
src/htdocs/js/scientific/ScientificSummaryModule.js

Scientific and Impact summary not working properly

---

src/htdocs/js/losspager/PAGERView.js
src/htdocs/js/map/ShakeMapStationLayer.js

Fix bug in shakemap station layer on interactive map.
Fixes #507 bug in pager view when pager has no impact comments (alert level pending).

Shakemap station layer hotfix

---

etc/events/us10004u1y.json
src/htdocs/js/general/GeneralSummaryModule.js
test/spec/general/GeneralSummaryModuleTest.js

Ensure that duplicate general-link products are not displayed on the General Summary page.

---

src/htdocs/js/dyfi/DYFIFormModule.js

Submit button not being enabled after location is set.

---

src/htdocs/js/dyfi/DYFIFormView.js

fixes usgs/earthquake-eventpages#512

added content for privacy statemnt

---

src/htdocs/js/core/EventPage.js

fixes usgs/earthquake-eventpages#516

moved Latest Earthquakes nav like to top of navigations links

---

src/htdocs/js/core/Module.js
test/spec/scientific/ScientificSummaryModuleTest.js

fixes usgs/earthquake-eventpages#434
- Added tests

Usgs/earthquake eventpages#434

---

src/htdocs/js/core/EventPage.js

Check if there are any contributors before attempting to build the contributor list in the footer
fixes #500

Remove contributor header from unknown.php 

---

src/htdocs/css/origin/_MagnitudesView.scss
src/htdocs/js/origin/MagnitudesView.js

Label preferred magnitude on magnitude tab.

---

src/htdocs/js/core/EventPage.js

Scroll to the top of the page when the hash changes.

---

src/htdocs/js/dyfi/DYFIIntensityGraphView.js

Update DYFIIntensityGraphView x axis labels.

---

src/htdocs/js/map/DyfiUtmLayer.js

fixes usgs/earthquake-eventpages#504

changed distance to use whole numbers

---

src/htdocs/js/dyfi/DYFIFormView.js
test/spec/dyfi/DYFIFormViewTest.js

Fix bug where confidence of -1 throws error

---

src/htdocs/js/general/GeneralSummaryModule.js

fixes usgs/earthquake-eventpages#541

removed text that was not needed

---

src/htdocs/css/core/_BasicPinView.scss
src/htdocs/js/core/BasicPinView.js
test/spec/core/BasicPinViewTest.js

Link Entire BasicPinView

---

src/htdocs/js/core/BasicPinView.js

_this.onClick should preventDefault on the MouseEvent, not _onClick

---

example/_navigation.inc.php
src/htdocs/js/losspager/PAGERPinView.js

Use the PAGERModule as the default module for PAGERPinVIew

---

example/_navigation.inc.php
example/dyfi/DYFIPinViewExample.js
example/dyfi/DYFIPinViewExample.php
gruntconfig/browserify.js
src/htdocs/css/event.scss
src/htdocs/js/dyfi/DYFIPinView.js
src/htdocs/js/general/ExecutiveSummaryModule.js
test/spec/dyfi/DYFIPinViewTest.js
test/test.js

DYFIPinView

---

example/_navigation.inc.php
example/dyfi/DYFIFormPinViewExample.js
example/dyfi/DYFIFormPinViewExample.php
gruntconfig/browserify.js
src/htdocs/css/dyfi/_DYFIFormPinView.scss
src/htdocs/css/event.scss
src/htdocs/js/dyfi/DYFIFormPinView.js
src/htdocs/js/general/ExecutiveSummaryModule.js
test/spec/dyfi/DYFIFormPinViewTest.js
test/test.js

DYFIFormPinView

---

src/htdocs/css/origin/_OriginPinView.scss
src/htdocs/js/general/ExecutiveSummaryModule.js
src/htdocs/js/origin/OriginPinView.js
src/htdocs/js/origin/OriginView.js
src/htdocs/js/scientific/ScientificSummaryModule.js
test/spec/origin/OriginPinViewTest.js

fixes usgs/earthquake-eventpages#551
- Changed Default module to OriginModule

changed default module to OriginModule

---

etc/events/us10004u1y_orig.json
example/_navigation.inc.php
example/dyfi/DYFIViewExample.php
example/map/InteractiveMapPinViewExample.js
example/map/InteractiveMapPinViewExample.php
example/map/InteractiveMapViewExample.js
gruntconfig/browserify.js
src/htdocs/js/general/ExecutiveSummaryModule.js
src/htdocs/js/map/InteractiveMapPinView.js
src/htdocs/js/map/InteractiveMapView.js
test/spec/map/InteractiveMapPinViewTest.js
test/test.js

Interactive Map Pin View #547

---

gruntconfig/browserify.js
gruntconfig/connect.js
src/htdocs/js/core/EventPage.js
src/htdocs/js/core/NearbySeismicity.js
src/htdocs/js/general/RegionalInfoModule.js
test/spec/core/NearbySeismicityTest.js
test/test.js

Nearby seismicity

---

example/dyfi/DYFIPinViewExample.php
src/htdocs/css/core/_BasicPinView.scss
src/htdocs/js/dyfi/DYFIPinView.js

Update DYFIPinView with new thumbnail add maxmmi to header

---

src/htdocs/css/losspager/_PAGERPinView.scss
src/htdocs/js/losspager/PAGERPinView.js
test/spec/losspager/PAGERPinViewTest.js

Do not use headers with PAGER histograms in PAGERPinView, add pager bubble to header

---

src/htdocs/css/finite-fault/_FiniteFaultPinView.scss
src/htdocs/js/finite-fault/FiniteFaultPinView.js
test/spec/finite-fault/FiniteFaultPinViewTest.js

Use cross-section of slip distribution image

---

src/htdocs/js/shakemap/ShakeMapPinView.js

Add impact bubble to header, use pin-thumbnail

---

src/htdocs/css/general/_RegionalInfoModule.scss
src/htdocs/js/general/RegionalInfoModule.js
test/spec/general/RegionalInfoModuleTest.js

Update RegionalInformationModule to display FE Regions similar to Admin Regions

---

src/htdocs/css/dyfi/_DYFIFormPinView.scss
src/htdocs/js/dyfi/DYFIFormPinView.js

left pad number of dyfi responses

---

src/htdocs/js/origin/OriginModule.js

Clear previous origin view after destroy

---

src/htdocs/js/core/EventPage.js

fixes usgs/earthquake-eventpages#610

Updated module nav order

---

gruntconfig/browserify.js
src/htdocs/css/event.scss
src/htdocs/css/oaf/_ForecastTableView.scss
src/htdocs/css/oaf/_OafModule.scss
src/htdocs/js/core/EventPage.js
src/htdocs/js/oaf/ForecastTableView.js
src/htdocs/js/oaf/ForecastTextView.js
src/htdocs/js/oaf/ForecastView.js
src/htdocs/js/oaf/ModelDetailsView.js
src/htdocs/js/oaf/OafModule.js
src/htdocs/js/oaf/OafView.js

This PR adds the initial work for the Aftershock forecast module to the event pages. This module will not appear unless on "oaf" product is sent for an event currently these are still in dev but having this code integrated is crucial for the QA/review process.

Operational Aftershock Forecasting

---

src/htdocs/js/general/ExecutiveSummaryModule.js

Move tsunami pin to the last position

---

src/htdocs/css/dyfi/_DYFIView.scss
src/htdocs/js/dyfi/DYFIFormView.js
src/htdocs/js/dyfi/DYFIModule.js

Add link below header on DYFI page that links to tell us form

---

src/htdocs/js/general/RegionalInfoModule.js

fixes usgs/earthquake-eventpages#642

Using first fe name/number to appear.

---

gruntconfig/postcss.js

Ensure that dist process does not strip autoprefixed css rules

---

src/htdocs/css/general/_RegionalInfoModule.scss
src/htdocs/js/general/RegionalInfoModule.js
test/spec/general/RegionalInfoModuleTest.js

fixes usgs/earthquake-eventpages#652

removed fe number from regional information and changed test

---

src/htdocs/css/core/_BasicPinView.scss
src/htdocs/css/losspager/_PAGERPinView.scss
src/htdocs/js/dyfi/DYFIPinView.js
src/htdocs/js/losspager/PAGERPinView.js

Fix impact bubble floats

---

src/htdocs/css/core/_BasicPinView.scss
src/htdocs/css/losspager/_PAGERPinView.scss
src/htdocs/js/losspager/PAGERPinView.js

fixes #654 
@jmfee-usgs do you like this better?

Reuse bubble stlyes

---

src/htdocs/js/losspager/PAGERView.js

Fixed typos

---

src/htdocs/js/languages/en.json

Update d_text to be d_text[]

---

src/htdocs/js/dyfi/DYFIIntensityGraphView.js

Update DYFIIntensityGraphView to only render once, not on every added dataset

---

src/htdocs/js/scientific/ScientificSummaryModule.js

Fix Nodal Plane typos

---

src/htdocs/js/core/Formatter.js
src/htdocs/js/dyfi/DYFIFormView.js
test/spec/core/FormatterTest.js

DYFI Form Bugs

---

src/htdocs/js/dyfi/DYFIFormView.js

@lisa-usgs is this what you wanted?

Move privacy statement to top of contact form

---

src/app/event.spec.ts
src/app/event.ts

Simplify event constructor, add unit tests

---

src/app/app.module.ts
src/app/event.ts
src/app/product-page/download/download.component.spec.ts
src/app/product-page/download/download.component.ts
src/app/quakeml.service.spec.ts
src/app/quakeml.service.ts
src/app/quakeml.spec.ts
src/app/quakeml.ts
src/app/xml-to-json.spec.ts
src/app/xml-to-json.ts

Needs tests, but can be used in origin/phases or origin/magnitudes.
Fixes #774

Add QuakemlService, Quakeml, and QuakemlEvent objects

---

src/app/event.spec.ts
src/app/event.ts
src/app/quakeml-event.ts
src/app/quakeml.ts
src/app/to-array.ts
src/app/to-index.ts
src/app/xml-to-json.ts

Fixes #774 
- separate files for classes/functions
- more tests
- fix linting errors

Issue 744 2

---

src/app/event.spec.ts
src/app/event.ts
src/app/executive/executive.module.ts
src/app/executive/executive/executive.component.html
src/app/executive/executive/executive.component.spec.ts
src/app/executive/executive/executive.component.ts
src/app/shared/link-product/link-product.component.html
src/app/shared/link-product/link-product.component.spec.ts
src/app/shared/link-product/link-product.component.ts
src/app/shared/shared.module.ts
src/app/shared/text-product/text-product.component.html
src/app/shared/text-product/text-product.component.spec.ts
src/app/shared/text-product/text-product.component.ts

Add tests for shared/TextProduct component

---

src/app/executive/executive/executive.component.html
src/app/executive/focal-mechanism-pin/focal-mechanism-pin.component.spec.ts
src/app/executive/focal-mechanism-pin/focal-mechanism-pin.component.ts

cleaned up code, added else for moment tensor

---

Dockerfile
Jenkinsfile.groovy
package-lock.json
package.json

Removes need for Git. Accelerates build. Still want to keep an eye out for updates to zone.js for release including this patch for jasmine. Prefer ultimately to use npm package.

Using tar.gz for zone.js dependency

---

src/app/shakemap/shakemap-routing.module.ts
src/app/shakemap/shakemap.module.ts
src/app/shakemap/shakemap/shakemap.component.html
src/app/shakemap/uncertainty/uncertainty.component.html
src/app/shakemap/uncertainty/uncertainty.component.spec.ts
src/app/shakemap/uncertainty/uncertainty.component.ts

Uncertainty component working

---

src/app/product-page/header/header.component.scss
src/app/product-page/header/header.component.ts

Update the styles for un/preferred and un/reviewed.

Add Quality Statement Styles

---

src/app/executive/origin-pin/origin-pin.component.scss
src/app/executive/region-info-pin/region-info-pin.component.ts
src/app/map/map/map.component.html
src/app/map/map/map.component.spec.ts
src/app/map/map/map.component.ts
src/app/region-info/region-info.module.ts
src/app/region-info/region-info/region-info.component.css
src/app/region-info/region-info/region-info.component.html
src/app/region-info/region-info/region-info.component.spec.ts
src/app/region-info/region-info/region-info.component.ts
src/app/shared/map-overlay/historic-seismicity-overlay.ts
src/app/shared/map-overlay/overlay.ts
src/app/shared/map/map.component.ts

fixes #846
fixes #862
fixes #864 
fixes #867 
fixes #868 
fixes #869 
fixes #870

Easy fixes

---

src/app/shakemap/metadata/input/input.component.html
src/app/shakemap/metadata/output/output.component.html
src/app/shakemap/metadata/processing/processing.component.html
src/app/shakemap/shakemap/shakemap.component.html
src/app/shakemap/uncertainty/uncertainty.component.html
src/app/shakemap/uncertainty/uncertainty.component.ts

closes #820, closes #821
unwrapped lines 80 characters and under
Applied preferred wrapping and indentation (described in #820) to `*ngIf` statements that I was indenting too far and to some long lines that were missed

Preferred indent and wrapping in shakemap module

---

src/app/tell-us/form-language.service.spec.ts
src/app/tell-us/form-language.service.ts
src/app/tell-us/form-language/en.json
src/app/tell-us/form-language/es.json
src/app/tell-us/form/form.component.html
src/app/tell-us/form/form.component.spec.ts
src/app/tell-us/form/form.component.ts
src/app/tell-us/tell-us.module.ts
src/app/tell-us/tell-us/tell-us.component.spec.ts
src/typings.d.ts

Load translation files into tell-us form.

Add form language service, english/spanish translations

---

package-lock.json
package.json
src/app/app.module.ts
src/app/region-info/region-info.module.ts
src/app/region-info/region-info/region-info.component.html
src/app/region-info/region-info/region-info.component.spec.ts
src/app/region-info/region-info/region-info.component.ts

Add geoserve components to region info component

---

.gitignore
src/app/shakemap/uncertainty/uncertainty.component.html

closes #821 
Also add .vscode dir to .gitignore

Add alt for uncertainty image

---

src/app/shared/interactive-map-overlays.pipe.ts
src/app/shared/map-overlay/landscan-population-overlay.ts

Add landscan population overlay to interactive map

---

package-lock.json
src/app/map/map/map.component.html
src/app/map/map/map.component.spec.ts
src/app/shared/css/leaflet-styles.scss
src/app/shared/css/legend-control.scss
src/app/shared/map-control/legend-control.scss
src/app/shared/map-control/legend-control.ts
src/app/shared/map/map.component.spec.ts
src/app/shared/map/map.component.ts
src/styles.scss

Add sharedLegendControl parameter to shared-map

---

src/app/app-routing.module.ts
src/app/pager/pager-routing.module.ts
src/app/pager/pager.module.ts
src/app/pager/pager/pager.component.html
src/app/pager/pager/pager.component.spec.ts
src/app/pager/pager/pager.component.ts

Pager Module

---

src/app/shakemap/shakemap.module.ts
src/app/shakemap/station-list/station-list.component.css
src/app/shakemap/station-list/station-list.component.html
src/app/shakemap/station-list/station-list.component.spec.ts
src/app/shared/station/station.component.css
src/app/shared/station/station.component.html
src/app/shared/station/station.component.spec.ts

closes #890
Removed the mat-card wrapper
Using a header with station name/code
Using shared-bubble components for the summary information
Combine station latitude/longitude into GPS Location
Implemented outlier flag for channel amplitudes

Station update

---

src/app/tell-us/form-language/en.json
src/app/tell-us/form-language/es.json
src/app/tell-us/form/form.component.html
src/app/tell-us/form/form.component.scss
src/app/tell-us/form/form.component.spec.ts
src/app/tell-us/form/form.component.ts
src/app/tell-us/question/question.component.html
src/app/tell-us/question/question.component.scss
src/app/tell-us/question/question.component.spec.ts
src/app/tell-us/question/question.component.ts

Issue 892 2

---

src/app/pager/pager/pager.component.ts
src/app/pager/pagerxml.service.ts

Pager XML fixes

---

src/app/event-page/navigation/navigation.component.html
src/app/event-page/navigation/navigation.component.spec.ts
src/app/event-page/navigation/navigation.component.ts

added ground failure link after pager

---

src/app/ground-failure/about/about.component.html

created ground failure about component

---

src/app/ground-failure/about/about.component.html

fixed link, updated phrasing, fixed quotes

---

package-lock.json
package.json

Update template to v2.2.0, with less navigation scrolling

---

src/app/executive/basic-pin/basic-pin.component.html
src/app/executive/executive/executive.component.html
src/app/executive/executive/executive.component.spec.ts
src/app/executive/shakemap-pin/shakemap-pin.component.html
src/app/executive/shakemap-pin/shakemap-pin.component.scss
src/app/executive/shakemap-pin/shakemap-pin.component.spec.ts
src/app/executive/shakemap-pin/shakemap-pin.component.ts

Replace map in shakemap pin

---

src/app/shared/mmi/mmi.component.html
src/app/shared/mmi/mmi.component.scss
src/app/shared/mmi/mmi.component.spec.ts
src/app/shared/mmi/mmi.component.ts
src/app/shared/station/station.component.html
src/app/shared/station/station.component.spec.ts

Add "bubble" option to shared-mmi component

---

src/app/ground-failure/summary/summary.component.html
src/app/ground-failure/summary/summary.component.spec.ts
src/app/ground-failure/summary/summary.component.ts

Set Map Bounds for Ground Failure on Interactive Map

---

src/app/shared/ground-failure-overlays.pipe.spec.ts
src/app/shared/map-overlay/ground-failure-landslide-overlay.spec.ts
src/app/shared/map-overlay/ground-failure-liquefaction-overlay.spec.ts

Add tests for ground-failure overlays

---

src/app/event-page/navigation/navigation.component.html
src/app/pager/pager/pager.component.html
src/app/pager/pager/pager.component.scss
src/app/pager/pager/pager.component.ts
src/app/pager/pagerxml.service.spec.ts
src/app/pager/pagerxml.service.ts

Create Pager Module

---

src/app/executive/origin-pin/origin-pin.component.html
src/app/executive/shakemap-pin/shakemap-pin.component.html
src/app/focal-mechanism/attribution/attribution.component.html
src/app/impact/dyfi-summary/dyfi-summary.component.html
src/app/moment-tensor/info/info.component.html

fixed ngIf in card content, switched to pipe for uppercase

---

src/app/ground-failure/population-alert/population-alert.component.ts

updated bins

---

package-lock.json
src/app/oaf/commentary/commentary.component.html
src/app/oaf/commentary/commentary.component.scss
src/app/oaf/commentary/commentary.component.spec.ts
src/app/oaf/commentary/commentary.component.ts
src/app/shared/percentage.pipe.spec.ts
src/app/shared/percentage.pipe.ts
src/app/shared/shared.module.ts
src/app/shared/significant-figure.pipe.spec.ts
src/app/shared/significant-figure.pipe.ts

fixes #991 
I understand that this could be refactored better. I just wanted to put in what i had before leaving.

OAF Commentary Tab

---

gruntconfig/connect.js
package.json
src/htdocs/js/map/InteractiveMapView.js
src/lib/configure.inc.php

- Clean npm install with 4.2.4
- Must run `php src/lib/pre-install.php`

Restrict zoom levels

---

src/app/dyfi/intensity/intensity.component.html
src/app/dyfi/intensity/intensity.component.spec.ts
src/app/dyfi/intensity/intensity.component.ts
src/app/dyfi/zip/zip.component.html
src/app/dyfi/zip/zip.component.spec.ts
src/app/dyfi/zip/zip.component.ts

DYFI Intensity and ZIP maps

---

src/app/oaf/commentary/commentary.component.html
src/app/oaf/commentary/commentary.component.spec.ts
src/app/oaf/forecast/forecast.component.ts
src/app/oaf/oaf-percent.pipe.ts

- Fixed typo in forecast table
- Updated Commentary text
- Commentary uses rounding pipes now

Oaf changes

---

src/app/core/dyfi.service.ts
src/app/dyfi/intensity-vs-distance/intensity-vs-distance.component.spec.ts
src/app/dyfi/intensity-vs-distance/intensity-vs-distance.component.ts
src/app/dyfi/responses-vs-time/responses-vs-time.component.spec.ts

Issue 1028

---

package-lock.json
src/app/oaf/commentary/commentary.component.html

Issue 1033

---

src/app/oaf/commentary/commentary.component.html

removed redundant text and showed 4th bullet point

---

src/app/executive/executive.module.ts
src/app/executive/executive/executive.component.html
src/app/executive/executive/executive.component.spec.ts
src/app/executive/finite-fault-pin/finite-fault-pin.component.html
src/app/executive/finite-fault-pin/finite-fault-pin.component.scss
src/app/executive/finite-fault-pin/finite-fault-pin.component.spec.ts
src/app/executive/finite-fault-pin/finite-fault-pin.component.ts
src/app/shared/product-content.pipe.spec.ts
src/app/shared/product-content.pipe.ts
src/app/shared/shared.module.ts

Issue 1038

---

src/app/oaf/forecast/forecast.component.html

changed the notation E to N in the forecast table

---

src/app/ground-failure/ground-failure/ground-failure.component.html

added logic to remove point source text

---

src/app/ground-failure/ground-failure/ground-failure.component.html

@jdbrown-USGS what do you think? There is one less if statement now.

Fix typo, simplify logic

---

angular.json
package-lock.json
package.json
src/app/app.module.ts
src/app/tell-us/form/form.component.html
src/app/tell-us/form/form.component.spec.ts
src/app/tell-us/form/form.component.ts
src/app/tell-us/location/location.component.html
src/app/tell-us/location/location.component.scss
src/app/tell-us/location/location.component.spec.ts
src/app/tell-us/location/location.component.ts
src/app/tell-us/tell-us.module.ts
src/app/tell-us/tell-us/tell-us.component.spec.ts

Fixes #894
Fixes #966 
This is the packaged hazdev-ng-location-input library, see the readme for directions on implementing the location input:
https://www.npmjs.com/package/hazdev-ng-location-input

Package the location input, use in Tell Us! form

---

package-lock.json
src/app/ground-failure/alert-bar/alert-bar.component.html
src/app/ground-failure/alert-bar/alert-bar.component.scss

fixes #1021 
- Triangles and labels made larger

Issue 1021

---

package.json
src/app/oaf/forecast/forecast.component.html
src/app/oaf/forecast/forecast.component.scss
src/app/oaf/oaf.service.spec.ts
tsconfig.json

Fixes #1030
- Remove and re-install document-register-element package in node_modules. Be sure you get 1.8.1 in order to fix angular/elements console errors.

Issue-1030

---

src/app/oaf/commentary-details/commentary-details.component.html
src/app/oaf/commentary-details/commentary-details.component.spec.ts
src/app/oaf/commentary/commentary.component.html
src/app/oaf/commentary/commentary.component.spec.ts
src/app/oaf/forecast/forecast.component.html
src/app/oaf/forecast/forecast.component.spec.ts
src/app/oaf/model/model.component.html
src/app/shared/number-with-separator.pipe.spec.ts
src/app/shared/number-with-separator.pipe.ts
src/app/shared/shared.module.ts

Issue-1062

---

package-lock.json
package.json
src/app/dyfi/dyfi.module.ts
src/app/dyfi/dyfi/dyfi.component.html
src/app/dyfi/dyfi/dyfi.component.spec.ts
src/app/ground-failure/ground-failure.module.ts
src/app/ground-failure/ground-failure/ground-failure.component.html
src/app/ground-failure/ground-failure/ground-failure.component.spec.ts
src/app/oaf/oaf.module.ts
src/app/oaf/oaf/oaf.component.html
src/app/oaf/oaf/oaf.component.spec.ts
src/app/origin/detail/detail.component.css
src/app/origin/origin.module.ts
src/app/origin/origin/origin.component.html
src/app/origin/origin/origin.component.spec.ts
src/app/shakemap/shakemap.module.ts
src/app/shakemap/shakemap/shakemap.component.html
src/app/shakemap/shakemap/shakemap.component.spec.ts
src/styles.scss

fixes #1071 
Don't forget to npm install.
Some of these styles should be moved into the template. I will create a separate PR.

Update to use material design component for tabs

---

src/app/executive/dyfi-pin/dyfi-pin.component.html
src/app/executive/dyfi-pin/dyfi-pin.component.scss
src/app/executive/dyfi-pin/dyfi-pin.component.spec.ts
src/app/executive/dyfi-pin/dyfi-pin.component.ts
src/app/executive/executive.module.ts
src/app/executive/executive/executive.component.html
src/app/executive/executive/executive.component.spec.ts

created dyfi pin, added pin to executive module, updated test

---

src/app/product-page/header/header.component.html
src/app/product-page/header/header.component.spec.ts
src/app/product-page/link.pipe.spec.ts
src/app/product-page/link.pipe.ts
src/app/product-page/product-page.module.ts
src/app/product-page/summary-link/summary-link.component.html
src/app/product-page/summary-link/summary-link.component.spec.ts
src/app/product-page/summary-link/summary-link.component.ts

Issue 1060

---

package-lock.json
package.json
src/app/shared/map/map.component.spec.ts
src/app/tell-us/form/form.component.spec.ts
src/app/tell-us/form/form.component.ts
src/app/tell-us/location/location.component.spec.ts
src/app/tell-us/location/location.component.ts
src/app/tell-us/tell-us.module.ts

fixes #966 
This is now coming from a different npm package:
https://www.npmjs.com/package/hazdev-ng-location-view
Which is being published from the hazdev-location-view project, and this PR:
https://github.com/usgs/hazdev-location-view/pull/90

Use hazdev-ng-location-view

---

src/app/tell-us/form-language/es.json

es.json typo

---

package-lock.json
src/app/executive/shakemap-pin/shakemap-pin.component.html
src/app/executive/shakemap-pin/shakemap-pin.component.scss

added fallback template to shakemap pin

---

package-lock.json
src/app/executive/nearby-seismicity-pin/nearby-seismicity-pin.component.html
src/app/executive/nearby-seismicity-pin/nearby-seismicity-pin.component.spec.ts
src/app/executive/nearby-seismicity-pin/nearby-seismicity-pin.component.ts

Issue 1053

---

src/app/waveforms/waveforms/waveforms.component.ts

destroyed subscription onDestroy

---

proxy.conf.js
src/app/tell-us/form/form.component.spec.ts
src/app/tell-us/form/form.component.ts
src/app/tell-us/location/location.component.spec.ts
src/app/tell-us/location/location.component.ts
src/app/tell-us/tell-us/tell-us.component.html
src/app/tell-us/tell-us/tell-us.component.spec.ts
src/app/tell-us/tell-us/tell-us.component.ts

DYFI Form Submit

---

src/app/dyfi/responses/responses.component.html
src/app/tell-us/form/form.component.html

Updated OMB #, added distance unit

---

package-lock.json
src/app/executive/basic-pin/basic-pin.component.scss
src/app/executive/basic-pin/basic-pin.component.ts

updated styles for basic pin

---

src/app/shared/map/map.component.scss

removed margin from shared map

---

src/app/executive/oaf-pin/oaf-pin.component.html

removed div wrapper

---

src/app/dyfi/responses/dialog-responses.html
src/app/executive/basic-pin/basic-pin.component.scss
src/app/executive/dyfi-pin/dyfi-pin.component.html
src/app/executive/dyfi-pin/dyfi-pin.component.scss
src/app/executive/dyfi-response-submit-pin/dyfi-response-submit-pin.component.html
src/app/executive/dyfi-response-submit-pin/dyfi-response-submit-pin.component.scss
src/app/executive/finite-fault-pin/finite-fault-pin.component.html
src/app/executive/finite-fault-pin/finite-fault-pin.component.scss
src/app/executive/focal-mechanism-pin/focal-mechanism-pin.component.html
src/app/executive/focal-mechanism-pin/focal-mechanism-pin.component.spec.ts
src/app/executive/moment-tensor-pin/moment-tensor-pin.component.html
src/app/executive/moment-tensor-pin/moment-tensor-pin.component.spec.ts
src/app/executive/pager-pin/pager-pin.component.html
src/app/executive/pager-pin/pager-pin.component.scss
src/app/executive/tsunami-pin/tsunami-pin.component.html
src/app/executive/tsunami-pin/tsunami-pin.component.scss
src/app/shared/alert-level/alert-level.component.html

standardized markup on all 'image' type pins

---

src/app/event-page/event-page/event-page.component.html
src/app/executive/pager-pin/pager-pin.component.html
src/app/executive/pager-pin/pager-pin.component.scss
src/app/executive/pager-pin/pager-pin.component.spec.ts
src/app/shared/beachball/beachball.component.ts

Issue 1109

---

src/app/executive/basic-pin/basic-pin.component.scss
src/app/executive/ground-failure-pin/ground-failure-pin.component.scss
src/app/executive/nearby-seismicity-pin/nearby-seismicity-pin.component.scss

Pull final pin styles together

---

package-lock.json
src/app/event-page/header/header.component.html

added beta info banner

---

src/htdocs/js/core/EventPage.js

suppress OAF

---

src/app/executive/basic-pin/basic-pin.component.scss
src/app/executive/focal-mechanism-pin/focal-mechanism-pin.component.html
src/app/executive/moment-tensor-pin/moment-tensor-pin.component.html
src/app/executive/oaf-pin/oaf-pin.component.html

updated pin components to show lighter headings, switched oaf pin components around, and changed figcaptions on all beach ball components

---

src/app/dyfi/dyfi.module.ts
src/app/dyfi/dyfi/dyfi.component.html
src/app/dyfi/dyfi/dyfi.component.scss
src/app/dyfi/dyfi/dyfi.component.spec.ts
src/app/dyfi/dyfi/dyfi.component.ts
src/app/dyfi/responses/responses.component.html
src/app/dyfi/responses/responses.component.scss
src/app/dyfi/responses/responses.component.spec.ts
src/app/dyfi/responses/responses.component.ts
src/app/shared/download-dialog/download-dialog.component.css

added 'download all dyfi responses' button

---

src/app/executive/basic-pin/basic-pin.component.scss
src/app/executive/executive/executive.component.scss
src/app/executive/focal-mechanism-pin/focal-mechanism-pin.component.html
src/app/executive/ground-failure-pin/ground-failure-pin.component.scss
src/app/executive/map-pin/map-pin.component.scss
src/app/executive/moment-tensor-pin/moment-tensor-pin.component.html
src/app/executive/oaf-pin/oaf-pin.component.html
src/app/executive/origin-pin/origin-pin.component.html
src/app/executive/region-info-pin/region-info-pin.component.css
src/app/pager/pager-cities/pager-cities.component.scss
src/app/pager/pager-population/pager-population.component.scss
src/app/pager/pager/pager.component.scss
src/app/shared/alert-level/alert-level.component.scss
src/app/shared/bubble/bubble.component.css
src/app/shared/css/mmi-colors.scss
src/app/shared/mmi/mmi.component.scss
src/styles.scss

fixes #1130 
This adds onto what @cswilson-usgs did. 
There are a few styles here for consistency on executive pins, but also there was a scoping issue in the pager styles that had an effect on the pins. Plus we needed to improve contrast ratios on the bubbles.

Fix consistency issues with styles

---

src/app/dyfi/dyfi/dyfi.component.html
src/app/dyfi/dyfi/dyfi.component.ts
src/app/ground-failure/ground-failure/ground-failure.component.html
src/app/oaf/oaf/oaf.component.html
src/app/origin/origin/origin.component.html
src/app/origin/origin/origin.component.spec.ts
src/app/origin/origin/origin.component.ts
src/app/product-page/product-page/product-page.component.html
src/app/shakemap/shakemap/shakemap.component.html

Fix tab indicator issue

---

src/app/dyfi/responses/responses.component.ts
src/app/shared/download-dialog/download-dialog.component.scss
src/app/shared/download-dialog/download-dialog.component.ts

fixed code inconsistencies

---

gruntconfig/browserify.js
src/htdocs/css/core/_BetaPinView.scss
src/htdocs/css/event.scss
src/htdocs/js/core/BetaPinView.js
src/htdocs/js/core/EventPage.js
src/htdocs/js/general/ExecutiveSummaryModule.js
test/spec/core/BetaPinViewTest.js
test/test.js

Beta link on current event pages

---

package.json

increment version number

---

src/app/region-info/region-info.module.ts
src/app/region-info/region-info/region-info.component.html
src/app/region-info/region-info/region-info.component.scss
src/app/region-info/region-info/region-info.component.spec.ts
src/app/region-info/region-info/region-info.component.ts

Update Region Info Module

---

src/app/waveforms/waveform.service.spec.ts
src/app/waveforms/waveform.service.ts
src/app/waveforms/waveforms-routing.module.ts
src/app/waveforms/waveforms.module.spec.ts
src/app/waveforms/waveforms.module.ts
src/app/waveforms/waveforms/waveforms.component.html
src/app/waveforms/waveforms/waveforms.component.scss
src/app/waveforms/waveforms/waveforms.component.spec.ts
src/app/waveforms/waveforms/waveforms.component.ts

Update Waveforms Module

---

src/app/dyfi/responses/responses.component.spec.ts
src/app/dyfi/responses/responses.component.ts

fixed headers order on the download dyfi button

---

src/app/shakemap/shakemap/shakemap.component.html
src/app/shakemap/shakemap/shakemap.component.spec.ts
src/app/shakemap/uncertainty/uncertainty.component.html
src/app/shakemap/uncertainty/uncertainty.component.spec.ts
src/app/shakemap/uncertainty/uncertainty.component.ts
src/app/shared/map-overlay/shakemap-psa03-overlay.ts
src/app/shared/map-overlay/shakemap-psa10-overlay.ts
src/app/shared/map-overlay/shakemap-psa30-overlay.ts

closes #1126 
And switch to using product-content.pipe

Implement new shakemap fallbacks

---

src/app/unknown-event-page/unknown-event-page.module.ts
src/app/unknown-event-page/unknown-event-page/unknown-event-page.component.html
src/app/unknown-event-page/unknown-event-page/unknown-event-page.component.spec.ts
src/app/unknown-event-page/unknown-event-page/unknown-event-page.component.ts

standardized unknown event files

---

src/app/tell-us/fieldset/fieldset.component.ts
src/app/tell-us/form-language.service.spec.ts
src/app/tell-us/form-language.service.ts
src/app/tell-us/form/form.component.html
src/app/tell-us/form/form.component.scss
src/app/tell-us/form/form.component.spec.ts
src/app/tell-us/form/form.component.ts
src/app/tell-us/location/location.component.scss
src/app/tell-us/location/location.component.spec.ts
src/app/tell-us/location/location.component.ts
src/app/tell-us/privacy-statement/privacy-statement.component.ts
src/app/tell-us/question/question.component.html
src/app/tell-us/question/question.component.scss
src/app/tell-us/question/question.component.spec.ts
src/app/tell-us/question/question.component.ts
src/app/tell-us/tell-us.module.ts
src/app/tell-us/tell-us/tell-us.component.html
src/app/tell-us/tell-us/tell-us.component.spec.ts
src/app/tell-us/tell-us/tell-us.component.ts

standardized all tell-us files

---

src/app/tell-us/fieldset/fieldset.component.ts
src/app/tell-us/form/form.component.html
src/app/tell-us/form/form.component.spec.ts
src/app/tell-us/form/form.component.ts
src/app/tell-us/location/location.component.ts
src/app/tell-us/question/question.component.ts
src/app/tell-us/tell-us/tell-us.component.ts

Small updates to tell-us module

---

src/app/finite-fault/finite-fault-routing.module.ts
src/app/finite-fault/finite-fault.module.ts
src/app/finite-fault/finite-fault/finite-fault.component.html
src/app/finite-fault/finite-fault/finite-fault.component.scss
src/app/finite-fault/finite-fault/finite-fault.component.spec.ts
src/app/finite-fault/finite-fault/finite-fault.component.ts

Update coding standards for finite fault module

---

src/app/map/map.module.ts
src/app/map/map/map.component.scss
src/app/map/map/map.component.spec.ts
src/app/map/map/map.component.ts

Update coding standards for map module

---

src/app/oaf/commentary-details/commentary-details.component.html
src/app/oaf/commentary-details/commentary-details.component.spec.ts
src/app/oaf/commentary-details/commentary-details.component.ts
src/app/oaf/commentary/commentary.component.html
src/app/oaf/commentary/commentary.component.spec.ts
src/app/oaf/commentary/commentary.component.ts
src/app/oaf/forecast/forecast.component.spec.ts
src/app/oaf/forecast/forecast.component.ts
src/app/oaf/model/model.component.scss
src/app/oaf/model/model.component.spec.ts
src/app/oaf/model/model.component.ts
src/app/oaf/oaf/oaf.component.html
src/app/oaf/oaf/oaf.component.spec.ts
src/app/oaf/oaf/oaf.component.ts
src/app/origin/phase/phase.component.spec.ts

OAF Updates

---

src/app/dyfi/dyfi.service.ts
src/app/dyfi/dyfi/dyfi.component.html
src/app/dyfi/dyfi/dyfi.component.spec.ts
src/app/dyfi/dyfi/dyfi.component.ts
src/app/dyfi/intensity-vs-distance/intensity-vs-distance.component.html
src/app/dyfi/intensity-vs-distance/intensity-vs-distance.component.spec.ts
src/app/dyfi/intensity-vs-distance/intensity-vs-distance.component.ts
src/app/dyfi/intensity/intensity.component.html
src/app/dyfi/intensity/intensity.component.ts
src/app/dyfi/responses-vs-time/responses-vs-time.component.html
src/app/dyfi/responses-vs-time/responses-vs-time.component.spec.ts
src/app/dyfi/responses-vs-time/responses-vs-time.component.ts
src/app/dyfi/responses/responses.component.html
src/app/dyfi/responses/responses.component.ts
src/app/dyfi/zip/zip.component.html
src/app/dyfi/zip/zip.component.ts

closes #1201 
closes #1155 
Add fallback products for intensity vs. distance and responses vs. time plots
Remove tabs when products aren't available (from #1196, the rest of this issue still needs addressing)
Remove extraneous OnInit implementations
General cleanup

Dyfi cleanup

---

src/app/dyfi/dyfi-routing.module.ts
src/app/dyfi/dyfi.module.ts
src/app/dyfi/dyfi.service.spec.ts
src/app/dyfi/dyfi.service.ts
src/app/dyfi/dyfi/dyfi.component.scss
src/app/dyfi/dyfi/dyfi.component.spec.ts
src/app/dyfi/dyfi/dyfi.component.ts
src/app/dyfi/intensity-vs-distance/intensity-vs-distance.component.spec.ts
src/app/dyfi/intensity-vs-distance/intensity-vs-distance.component.ts
src/app/dyfi/intensity/intensity.component.spec.ts
src/app/dyfi/intensity/intensity.component.ts
src/app/dyfi/responses-vs-time/responses-vs-time.component.spec.ts
src/app/dyfi/responses-vs-time/responses-vs-time.component.ts
src/app/dyfi/responses/responses.component.html
src/app/dyfi/responses/responses.component.scss
src/app/dyfi/responses/responses.component.spec.ts
src/app/dyfi/responses/responses.component.ts
src/app/dyfi/zip/zip.component.spec.ts
src/app/dyfi/zip/zip.component.ts

Updates to coding standards

---

src/app/core/contents-xml.service.spec.ts
src/app/core/contents-xml.service.ts
src/app/core/contributor.service.spec.ts
src/app/core/contributor.service.ts
src/app/core/core.module.ts
src/app/core/event.service.spec.ts
src/app/core/event.service.ts
src/app/core/formatter.service.spec.ts
src/app/core/formatter.service.ts
src/app/core/geoserve.service.spec.ts
src/app/core/geoserve.service.ts
src/app/core/metadata.service.spec.ts
src/app/core/metadata.service.ts
src/app/core/quakeml.service.spec.ts
src/app/core/quakeml.service.ts
src/app/core/station.service.spec.ts
src/app/core/station.service.ts

Issue 1154 standardize core module

---

src/app/event-page/contributor-list.pipe.ts
src/app/event-page/event-date-time.pipe.ts
src/app/event-page/event-depth.pipe.ts
src/app/event-page/event-location.pipe.ts
src/app/event-page/event-page.module.ts
src/app/event-page/event-page/event-page.component.ts
src/app/event-page/event-title.pipe.ts
src/app/event-page/header/header.component.scss
src/app/event-page/navigation/navigation.component.ts

Update event-page module

---

package-lock.json
src/app/core/contents-xml.service.spec.ts
src/app/core/contents-xml.service.ts
src/app/core/contributor.service.spec.ts
src/app/core/contributor.service.ts
src/app/core/event.service.spec.ts
src/app/core/event.service.ts
src/app/core/formatter.service.ts
src/app/core/geoserve.service.spec.ts
src/app/core/geoserve.service.ts
src/app/core/metadata.service.spec.ts
src/app/core/metadata.service.ts
src/app/core/quakeml.service.spec.ts
src/app/core/quakeml.service.ts
src/app/core/station.service.spec.ts
src/app/core/station.service.ts
src/app/shared/dyfi-counter.pipe.ts
src/app/shared/map/map.component.ts

Issue 1154

---

src/app/shakemap/intensity/intensity.component.html
src/app/shakemap/metadata/input/input.component.spec.ts
src/app/shakemap/metadata/input/input.component.ts
src/app/shakemap/metadata/metadata.component.html
src/app/shakemap/metadata/metadata.component.ts
src/app/shakemap/metadata/output/output.component.html
src/app/shakemap/metadata/output/output.component.spec.ts
src/app/shakemap/metadata/output/output.component.ts
src/app/shakemap/metadata/processing/processing.component.html
src/app/shakemap/metadata/processing/processing.component.spec.ts
src/app/shakemap/metadata/processing/processing.component.ts
src/app/shakemap/pga/pga.component.spec.ts
src/app/shakemap/pgv/pgv.component.spec.ts
src/app/shakemap/pgv/pgv.component.ts
src/app/shakemap/shakemap-routing.module.ts
src/app/shakemap/shakemap.module.ts
src/app/shakemap/shakemap/shakemap.component.spec.ts
src/app/shakemap/station-list/station-list.component.scss
src/app/shakemap/station-list/station-list.component.ts
src/app/shakemap/uncertainty/uncertainty.component.html
src/app/shakemap/uncertainty/uncertainty.component.ts

Shakemap coding standards update

---

src/app/core/event.service.spec.ts
src/app/core/event.service.ts
src/app/tell-us/tell-us/tell-us.component.spec.ts
src/app/tell-us/tell-us/tell-us.component.ts
src/app/waveforms/waveform.service.spec.ts

fixed changes and updated waveforms testing file

---

package-lock.json
package.json
src/app/app-routing.module.ts
src/app/app.module.ts
src/app/wildcard/wildcard-routing.module.ts
src/app/wildcard/wildcard.module.spec.ts
src/app/wildcard/wildcard.module.ts
src/app/wildcard/wildcard/wildcard.component.html
src/app/wildcard/wildcard/wildcard.component.spec.ts
src/app/wildcard/wildcard/wildcard.component.ts

Added wildcard module/lazy loaded

---

src/app/wildcard/wildcard/wildcard.component.html
src/app/wildcard/wildcard/wildcard.component.ts

fixed wording on wildcard route

---

package-lock.json
package.json

fixes #1230 
- npm run stats    to use analyzer

added webpack-bundle-analyzer

---

src/app/dyfi/responses/dialog-responses.html
src/app/dyfi/responses/responses.component.ts
src/app/event-page/event-page/event-page.component.html
src/app/event-page/event-page/event-page.component.ts
src/app/executive/executive/executive.component.html
src/app/impact/impact/impact.component.html
src/app/moment-tensor/axes/axes.component.ts
src/app/origin/magnitude-detail/magnitude-detail.component.ts
src/app/shakemap/station-list/station-list.component.html
src/app/shared/beachball/beachball.component.ts
src/app/shared/download-dialog/download-dialog.component.ts
src/app/shared/ngx-charts/bubble-line-chart/bubble-line-chart/bubble-line-chart.component.html
src/app/shared/ngx-charts/line-chart/line-chart/line-chart.component.html
src/app/shared/ngx-charts/line-chart/line-chart/line-chart.component.ts
src/app/shared/product-attribution/product-attribution.component.html
src/app/shared/product-attribution/product-attribution.component.ts
src/app/technical/technical/technical.component.html
src/app/tell-us/question/question.component.html

Issue 1234

---

src/app/dyfi/dyfi/dyfi.component.html
src/app/shakemap/intensity/intensity.component.html
src/app/shakemap/shakemap/shakemap.component.html

added static links on both DYFI and shakemap components

---

angular.json
package-lock.json
package.json
src/app/event-page/event-page.module.ts
src/app/event-page/event-page/event-page.component.html
src/app/event-page/event-page/event-page.component.spec.ts
src/app/event-page/navigation/navigation.component.html
src/app/event-page/navigation/navigation.component.spec.ts
src/app/region-info/region-info.module.ts
src/app/region-info/region-info/region-info.component.html
src/app/region-info/region-info/region-info.component.spec.ts
src/app/region-info/region-info/region-info.component.ts
src/app/tell-us/form/form.component.html
src/app/tell-us/form/form.component.ts
src/app/tell-us/location/location.component.html
src/app/tell-us/location/location.component.scss
src/app/tell-us/location/location.component.spec.ts
src/app/tell-us/location/location.component.ts
src/app/unknown-event-page/unknown-event-page.module.ts
src/app/unknown-event-page/unknown-event-page/unknown-event-page.component.html
src/app/unknown-event-page/unknown-event-page/unknown-event-page.component.spec.ts

#fixes #1228 
This uses the new angular 6 libraries for:
- hazdev-ng-location-view
- hazdev-ng-geoserve-output
- hazdev-ng-template

Implement updated dependencies

---

src/app/event-page/event-page/event-page.component.ts

Issue 1263

---

src/app/tell-us/form/form.component.html
src/app/tell-us/form/form.component.ts

added event boolean to tellus form to either show or not show the time input for events vs. unknown tellus form

---

package-lock.json
src/app/origin/detail/detail.component.html
src/app/origin/detail/detail.component.scss
src/app/shared/css/description-table.scss

added css styles to .description-table class

---

src/app/technical/finite-fault-summary/finite-fault-summary.component.html
src/app/technical/finite-fault-summary/finite-fault-summary.component.scss
src/app/technical/finite-fault-summary/finite-fault-summary.component.spec.ts
src/app/technical/finite-fault-summary/finite-fault-summary.component.ts
src/app/technical/origin-summary/origin-summary.component.html
src/app/technical/technical.module.ts
src/app/technical/technical/technical.component.html
src/app/technical/technical/technical.component.spec.ts

Issue 1191

---

src/app/dyfi/dyfi.service.spec.ts
src/app/dyfi/dyfi.service.ts
src/app/dyfi/intensity-vs-distance/intensity-vs-distance.component.spec.ts
src/app/dyfi/responses-vs-time/responses-vs-time.component.spec.ts
src/app/dyfi/responses/responses.component.spec.ts

DYFI Test coverage

---

src/app/shared/ngx-charts/bubble-chart/bubble-series/bubble-series.component.spec.ts
src/app/shared/ngx-charts/bubble-line-chart/bubble-line-chart/bubble-line-chart.component.spec.ts
src/app/shared/ngx-charts/bubble-line-chart/bubble-line-chart/bubble-line-chart.component.ts
src/app/shared/ngx-charts/line-chart/line-series/line-series.component.spec.ts
src/app/shared/ngx-charts/line-chart/line-series/line-series.component.ts

Add test coverage for ngx-charts

---

src/app/shared/interactive-map-overlays.pipe.ts
src/app/shared/map-overlay/mouse-over-layer.ts
src/app/shared/map-overlay/tectonic-plates-overlay.ts
src/app/shared/map-overlay/us-faults-overlay.ts
src/app/shared/map-overlay/utf-grid.ts
src/app/shared/map/map.component.html
src/app/shared/map/map.component.scss
src/app/shared/map/map.component.ts

Faults and Plates overlay

---

src/app/oaf/commentary/commentary.component.html

fixed wording in oaf what we think will happen next section

---

src/app/event-page/cooperator.pipe.spec.ts
src/app/event-page/cooperator.pipe.ts
src/app/event-page/event-page.module.ts
src/app/event-page/event-page/event-page.component.html
src/app/event-page/event-page/event-page.component.spec.ts
src/app/event-page/event-page/event-page.component.ts
src/app/shared/shared.module.ts

Depends on https://github.com/usgs/hazdev-template/pull/300
Fixes #1190
Review and merge dependency first. Then build and deploy hazdev-template under new version number. Update package.json to reference latest version of template.
Note: Travis will fail until dependency merged/published and package.json updated.

Issue-1190

---

package.json

increment hazdev-ng-template

---

src/app/oaf/forecast/forecast.component.html

Issue-1141

---

src/app/shared/significant-figure.pipe.spec.ts
src/app/shared/significant-figure.pipe.ts

Issue-1139

---

src/app/oaf/commentary/commentary.component.html
src/app/oaf/commentary/commentary.component.spec.ts

Issue-1138

---

src/app/oaf/forecast/forecast.component.html

added footnote

---

src/app/core/event.service.ts

added skipLocationChange

---

package-lock.json
src/app/finite-fault/create-segments.pipe.spec.ts
src/app/finite-fault/create-segments.pipe.ts
src/app/finite-fault/finite-fault.module.ts
src/app/finite-fault/finite-fault/finite-fault.component.html
src/app/finite-fault/finite-fault/finite-fault.component.spec.ts
src/app/finite-fault/result-table/result-table.component.html
src/app/finite-fault/result-table/result-table.component.scss
src/app/finite-fault/result-table/result-table.component.spec.ts
src/app/finite-fault/result-table/result-table.component.ts
src/app/finite-fault/segment.ts

Issue 1192

---

src/app/finite-fault/finite-fault/finite-fault.component.html

Hide finite fault scientific analysis section when not provided

---

src/app/ground-failure/ground-failure/ground-failure.component.html

fixes #1299 
- ground failure event us2000dvwq

removed text, made text bold

---

package-lock.json
src/app/core/formatter.service.ts
src/app/shared/dyfi-overlays.pipe.spec.ts
src/app/shared/dyfi-overlays.pipe.ts
src/app/shared/dyfi-response-popup/dyfi-response-popup.component.html
src/app/shared/dyfi-response-popup/dyfi-response-popup.component.scss
src/app/shared/dyfi-response-popup/dyfi-response-popup.component.spec.ts
src/app/shared/dyfi-response-popup/dyfi-response-popup.component.ts
src/app/shared/interactive-map-overlays.pipe.ts
src/app/shared/map-overlay/dyfi-response-overlay.spec.ts
src/app/shared/map-overlay/dyfi-response-overlay.ts
src/app/shared/shared.module.ts

fixed overlays bug and linting errors

---

src/app/ground-failure/ground-failure/ground-failure.component.html
src/app/ground-failure/ground-failure/ground-failure.component.spec.ts
src/app/pager/pager/pager.component.html
src/app/pager/pager/pager.component.spec.ts
src/app/product-page/header/header.component.html
src/app/product-page/header/header.component.scss
src/app/product-page/header/header.component.spec.ts
src/app/product-page/header/header.component.ts
src/app/product-page/product-page/product-page.component.html
src/app/product-page/product-page/product-page.component.spec.ts
src/app/product-page/product-page/product-page.component.ts
src/app/shakemap/shakemap/shakemap.component.html
src/app/shakemap/shakemap/shakemap.component.spec.ts

fixes #1296 
- Only shows version if a version is set to true and a version is found in product properties.

Issue 1296

---

package.json

fixes #1240 
Also,
- fixes banner/social images

Increment template version for current page highlighting in navigation

---

src/app/ground-failure/hazard-alert/hazard-alert.component.html
src/app/ground-failure/population-alert/population-alert.component.html

Fixes #1298 
No more mad libs. Simple (if repetitive) logic. Ask if you need link to original document describing changes.

Issue-1298

---

src/app/executive/pager-pin/pager-pin.component.html
src/app/executive/pager-pin/pager-pin.component.spec.ts
src/app/executive/pager-pin/pager-pin.component.ts
src/app/pager/pager/pager.component.spec.ts
src/app/pager/pager/pager.component.ts
src/environments/environment.ts

Issue 1282

---

src/app/shakemap/shakemap/shakemap.component.html
src/app/shakemap/station-list/station-list.component.html
src/app/shakemap/station-list/station-list.component.ts

Displaying a message for empty station lists

---

src/app/event-page/header/header.component.html

removed beta banner

---

src/app/ground-failure/alert-bar/alert-bar.component.html

added logic to show small values

---

src/app/ground-failure/population-alert/population-alert.component.ts

changed min bin for liquefaction

---

src/index.html

fixes #1312 
I was unable to get the custom events to work. The given example did not work for me.

added google analytics

---

src/app/dyfi/dyfi.module.ts
src/app/dyfi/responses/responses.component.html
src/app/dyfi/responses/responses.component.scss
src/app/dyfi/responses/responses.component.spec.ts
src/app/dyfi/responses/responses.component.ts
src/app/shared/ngx-charts/bubble-line-chart/bubble-line-chart/bubble-line-chart.component.html

closes #1349 
Using filter built into `MatTableDataSource`
Download is using filtered data instead of the entire dataset

Filter DYFI responses

---

src/app/shared/finite-fault-map-popup/finite-fault-map-popup.component.scss

Update finite-fault popup to fit on mobile

---

src/app/executive/ground-failure-pin/ground-failure-pin.component.scss
src/app/ground-failure/ground-failure/ground-failure.component.scss
src/app/ground-failure/ground-failure/ground-failure.component.ts
src/app/ground-failure/hazard-alert/hazard-alert.component.scss
src/app/ground-failure/population-alert/population-alert.component.scss

Small fixes for ground-failure

---

src/app/executive/shakemap-pin/shakemap-pin.component.html
src/app/executive/shakemap-pin/shakemap-pin.component.scss
src/app/executive/shakemap-pin/shakemap-pin.component.spec.ts
src/app/executive/shakemap-pin/shakemap-pin.component.ts

closes #1318 
Added new shakemap thumbnail, using data-based view as a fallback

Add shakemap thumbnail to pin

---

src/app/executive/executive/executive.component.html
src/app/executive/executive/executive.component.spec.ts
src/app/product-page/download/download.component.html
src/app/product-page/download/download.component.spec.ts
src/app/product-page/download/download.component.ts
src/app/product-page/product-page.module.ts

Add download for earthquake poster

---

src/app/core/formatter.service.spec.ts
src/app/core/formatter.service.ts

Fix magnitude type on origin details table

---

src/app/shared/fe-region/fe-region.component.html
src/app/shared/fe-region/fe-region.component.spec.ts
src/app/shared/fe-region/fe-region.component.ts

Fix fe region section

---

package.json

increment template version

---

package-lock.json
src/app/impact/dyfi-summary/dyfi-summary.component.html
src/app/impact/impact/impact.component.html
src/app/impact/impact/impact.component.spec.ts
src/app/impact/pager-summary/pager-summary.component.html
src/app/impact/shakemap-summary/shakemap-summary.component.html
src/app/shared/get-products.pipe.spec.ts
src/app/shared/get-products.pipe.ts
src/app/shared/has-product.pipe.spec.ts
src/app/shared/has-product.pipe.ts
src/app/shared/shared.module.ts
src/app/technical/focal-mechanism-summary/focal-mechanism-summary.component.html
src/app/technical/moment-tensor-summary/moment-tensor-summary.component.html
src/app/technical/origin-summary/origin-summary.component.html
src/app/technical/technical/technical.component.html
src/app/technical/technical/technical.component.spec.ts
src/app/technical/technical/technical.component.ts

fixes #1364 
finite-fault event: us1000h3p4

Issue 1364

---

src/app/origin/detail/detail.component.scss
src/app/pager/pager/pager.component.scss

Fix definition list styles (.description-table)

---

src/app/event-page/event-page/event-page.component.html
src/app/event-page/event-page/event-page.component.spec.ts

Issue 1374

---

src/app/tell-us/form/form.component.html
src/app/tell-us/form/form.component.ts
src/app/tell-us/tell-us/tell-us.component.ts

need to test ios scroll fix for tell us modal

---

package-lock.json
package.json

Increment template dependency for navigation bug fix and banner/social images

---

package-lock.json
package.json

Increment hazdev-ng-geoserve-output to fix undefined issue with compass winds calculation

---

src/app/shared/coordinates/coordinates.component.html

added non-breaking space in between the shared coordinates component

---

src/app/tell-us/tell-us/tell-us.component.html
src/app/tell-us/tell-us/tell-us.component.spec.ts
src/app/tell-us/tell-us/tell-us.component.ts

DYFI Submission Bug

---

src/app/finite-fault/finite-fault.module.ts
src/app/finite-fault/finite-fault/finite-fault.component.html
src/app/finite-fault/finite-fault/finite-fault.component.spec.ts
src/app/shared/get-map-bounds.pipe.spec.ts
src/app/shared/get-map-bounds.pipe.ts
src/app/shared/shared.module.ts

- fixes #1395 
- Finite Fault event: us1000h3p4

Issue 1395

---

src/app/shared/map/map.component.spec.ts
src/app/shared/map/map.component.ts

fixed panning from north/south on interactive map

---

src/app/tell-us/form/form.component.html

updated question order

---

package-lock.json
package.json

increment version number for template

---

src/app/event-page/event-page/event-page.component.ts

Fix, use the correct property name

---

package-lock.json
package.json

Update hazdev template for side navigation closing fix

---

src/app/shakemap/intensity/intensity.component.html
src/app/shakemap/intensity/intensity.component.spec.ts
src/app/shakemap/pga/pga.component.html
src/app/shakemap/pga/pga.component.spec.ts
src/app/shakemap/pgv/pgv.component.html
src/app/shakemap/pgv/pgv.component.spec.ts
src/app/shakemap/psa/psa.component.html
src/app/shakemap/psa/psa.component.spec.ts

Shakemap using sharedGetMapBounds pipe

---

src/app/executive/shakemap-pin/shakemap-pin.component.html
src/app/executive/shakemap-pin/shakemap-pin.component.spec.ts
src/app/executive/shakemap-pin/shakemap-pin.component.ts
src/app/shared/shaking-impact.pipe.spec.ts
src/app/shared/shaking-impact.pipe.ts
src/app/shared/shared.module.ts

Closes #1423
Now using sharedProductProperty pipe
Made new sharedShakingImpact pipe to do the impact description generation

Shakemap pin handles null, '-', '--' maxshaking values

---

src/app/core/formatter.service.spec.ts
src/app/core/formatter.service.ts
src/app/shakemap/metadata/output/output.component.html

Issue 1391

---

package-lock.json
package.json
src/app/event-page/event-page/event-page.component.spec.ts
src/app/event-page/event-page/event-page.component.ts

Update template and facebook meta data for sharing

---

package.json

Updated package.json to the newest app version, 1.16.0

Updated package.json to 1.16.0

---

package-lock.json
package.json
src/app/map/map.module.ts
src/app/map/map/map.component.html
src/app/map/map/map.component.scss
src/app/map/map/map.component.spec.ts
src/app/map/map/map.component.ts
src/app/shared/css/leaflet-styles.scss
src/app/shared/map/map.component.ts

Fullscreen Interactive Map

---

src/app/executive/dyfi-pin/dyfi-pin.component.html
src/app/executive/dyfi-pin/dyfi-pin.component.spec.ts

closes #1355
Using the new thumbnail on the DYFI pin

Using new DYFI thumbnail

---

src/app/app.component.ts
src/index.html

Warn users with iOS9 that they need to upgrade

---

src/app/shared/map-overlay/shakemap-stations-overlay.ts

closes #1452
Add CIIM as dyfi network for shakemap stations map layer

Recognize CIIM network stations as DYFI

---

src/app/shakemap/metadata/output/output.component.html
src/app/shakemap/metadata/output/output.component.scss
src/app/shakemap/metadata/processing/processing.component.html
src/app/shakemap/metadata/processing/processing.component.scss

set up horizontal scrolling

---

src/app/dyfi/intensity/intensity.component.html

closes #1453 
Show 10km dyfi layer after clicking on the intensity image

DYFI default map layer

---

src/app/shared/css/leaflet-styles.scss
src/app/shared/map/map.component.ts
src/index.html

Fix mouse position control

---

angular.json
package-lock.json
package.json
src/app/core/event.service.spec.ts
src/app/core/event.service.ts
src/environments/environment.scenario-prod.ts
src/environments/environment.scenario.ts
src/environments/environment.ts

Add Scenario Environment

---

src/app/event-page/header/header.component.html
src/app/event-page/header/header.component.ts

added banner when scenario is true

---

src/app/core/contributor.service.ts
src/app/dyfi/intensity-vs-distance/intensity-vs-distance.component.spec.ts
src/app/finite-fault/create-segments.pipe.spec.ts
src/app/finite-fault/create-segments.pipe.ts
src/app/shared/map-control/legend-control.spec.ts
src/app/shared/map-overlay/asynchronous-geojson-overlay.spec.ts
src/app/shared/map-overlay/shakemap-contours-overlay.spec.ts
src/app/shared/map-overlay/utf-grid.ts
src/app/shared/map/map.component.spec.ts
src/app/shared/mobile-check.pipe.ts
src/app/shared/ngx-charts/bubble-line-chart/bubble-line-chart/bubble-line-chart.component.spec.ts
src/app/shared/shakemap-overlays.pipe.spec.ts
src/app/tell-us/location/location.component.spec.ts
src/app/tell-us/tell-us/tell-us.component.spec.ts
src/app/wildcard/wildcard/wildcard.component.ts

Fixed test suite, added expectations and removed erroneous logs/error messages

---

package.json
proxy.conf.js
src/app/event-page/navigation/navigation.component.html
src/app/event-page/navigation/navigation.component.spec.ts
src/app/event-page/navigation/navigation.component.ts

Clean up navigation for scenario pages

---

src/app/scenario-event.spec.ts
src/app/scenario-event.ts

Created ScenarioEvent class to deal with scenario events

---

angular.json
package-lock.json
package.json
src/app/core/event.service.ts
src/app/event-page/event-page/event-page.component.html
src/app/event-page/header/header.component.html
src/app/event-page/header/header.component.spec.ts
src/app/event-page/header/header.component.ts
src/app/event-page/navigation/navigation.component.html
src/app/event-page/navigation/navigation.component.spec.ts
src/app/event-page/navigation/navigation.component.ts
src/app/scenario-event.ts
src/app/shared/is-actual-event.pipe.spec.ts
src/app/shared/is-actual-event.pipe.ts
src/app/shared/is-scenario-event.pipe.spec.ts
src/app/shared/is-scenario-event.pipe.ts
src/app/shared/shared.module.ts
src/environments/environment.prod.ts
src/environments/environment.ts

Used data-driven approach, created event and scenarioEvent pipes to return instanceof boolean

---

hooks/05-scenario-flag.sh

the main bundle does not have true/false it has !0/!1

update scenario hook to check for true/false after bundle is compiled

---

src/app/executive/executive/executive.component.html
src/app/executive/executive/executive.component.spec.ts

Fixes #1513 
- Only show pin for actual events (see change on line 17).
- Also, lots of white space/formatting changes ... prettier.

Issue-1513

---

src/app/map/map/map.component.html
src/app/map/map/map.component.scss
src/app/map/map/map.component.spec.ts

fixes #1520
- map.component.html  - change is from line 5 to 10

Issue 1520

---

src/app/executive/executive/executive.component.html

Issue 1517

---

src/app/app-routing.module.ts
src/app/shake-alert/shake-alert-routing.module.ts
src/app/shake-alert/shake-alert.module.spec.ts
src/app/shake-alert/shake-alert.module.ts
src/app/shake-alert/shake-alert/shake-alert.component.html
src/app/shake-alert/shake-alert/shake-alert.component.spec.ts
src/app/shake-alert/shake-alert/shake-alert.component.ts

#1527 
Reopen this ticket after merging

Issue 1527

---

src/app/shake-alert/shake-alert.module.ts
src/app/shake-alert/shake-alert.service.spec.ts
src/app/shake-alert/shake-alert.service.ts
src/app/shake-alert/shake-alert/shake-alert.component.html
src/app/shake-alert/shake-alert/shake-alert.component.spec.ts
src/app/shake-alert/shake-alert/shake-alert.component.ts

fixes #1527 
Needs some tests still.

Scaffold out the shake-alert component and service

---

src/app/shake-alert/shake-alert.module.ts
src/app/shake-alert/shake-alert/shake-alert-missed/shake-alert-missed.component.html
src/app/shake-alert/shake-alert/shake-alert-missed/shake-alert-missed.component.spec.ts
src/app/shake-alert/shake-alert/shake-alert-missed/shake-alert-missed.component.ts
src/app/shake-alert/shake-alert/shake-alert.component.html
src/app/shake-alert/shake-alert/shake-alert.component.spec.ts

Added shake-alert-missed component

---

src/app/shake-alert/shake-alert-confirmed/shake-alert-confirmed.component.html
src/app/shake-alert/shake-alert-confirmed/shake-alert-confirmed.component.scss
src/app/shake-alert/shake-alert-confirmed/shake-alert-confirmed.component.spec.ts
src/app/shake-alert/shake-alert-confirmed/shake-alert-confirmed.component.ts
src/app/shake-alert/shake-alert.module.ts
src/app/shake-alert/shake-alert/shake-alert.component.html
src/app/shake-alert/shake-alert/shake-alert.component.spec.ts

Create scaffolding for shake-alert-confirmed component

---

src/app/shake-alert/shake-alert-deleted/shake-alert-deleted.component.html
src/app/shake-alert/shake-alert-deleted/shake-alert-deleted.component.spec.ts
src/app/shake-alert/shake-alert-deleted/shake-alert-deleted.component.ts
src/app/shake-alert/shake-alert.module.ts
src/app/shake-alert/shake-alert/shake-alert-missed/shake-alert-missed.component.html
src/app/shake-alert/shake-alert/shake-alert-pending/shake-alert-pending.component.html
src/app/shake-alert/shake-alert/shake-alert.component.html
src/app/shake-alert/shake-alert/shake-alert.component.spec.ts

Create shake-alert-deleted component

---

src/app/shake-alert/shake-alert-confirmed/shake-alert-confirmed.component.html
src/app/shake-alert/shake-alert-confirmed/shake-alert-confirmed.component.scss
src/app/shake-alert/shake-alert-confirmed/shake-alert-confirmed.component.spec.ts
src/app/shake-alert/shake-alert/shake-alert.component.html

Update shake-alert-confirmed component to look more like the PDF mock

---

src/app/event-page/navigation/navigation.component.html
src/app/event-page/navigation/navigation.component.spec.ts
src/app/event-page/navigation/navigation.component.ts

Add shake-alert to the side navigation

---

src/app/shake-alert/shake-alert/shake-alert.component.html
src/app/shared/summary-link.pipe.ts

Fix error, add shake-alert to side navigation

---

src/app/shake-alert/shake-alert-confirmed/shake-alert-confirmed.component.html
src/app/shake-alert/shake-alert-confirmed/shake-alert-confirmed.component.spec.ts
src/app/shake-alert/shake-alert-nearby-cities/shake-alert-nearby-cities.component.html
src/app/shake-alert/shake-alert-nearby-cities/shake-alert-nearby-cities.component.scss
src/app/shake-alert/shake-alert-nearby-cities/shake-alert-nearby-cities.component.spec.ts
src/app/shake-alert/shake-alert-nearby-cities/shake-alert-nearby-cities.component.ts
src/app/shake-alert/shake-alert.module.ts

Issue 1530

---

src/app/shake-alert/shake-alert-confirmed/shake-alert-confirmed.component.html
src/app/shake-alert/shake-alert-confirmed/shake-alert-confirmed.component.scss
src/app/shake-alert/shake-alert-confirmed/shake-alert-confirmed.component.spec.ts
src/app/shake-alert/shake-alert-confirmed/shake-alert-confirmed.component.ts
src/app/shake-alert/shake-alert-summary-report/shake-alert-summary-report.component.html
src/app/shake-alert/shake-alert-summary-report/shake-alert-summary-report.component.spec.ts
src/app/shake-alert/shake-alert-summary-report/shake-alert-summary-report.component.ts
src/app/shake-alert/shake-alert.module.ts
src/app/shake-alert/shake-alert/shake-alert.component.html
src/app/shake-alert/shake-alert/shake-alert.component.spec.ts

fixes #1555 
This will allow EEW group to see what data we do not have.

Add summary report section to shake-alert-confirmed

---

src/app/shake-alert/shake-alert-deleted/shake-alert-deleted.component.ts
src/app/shake-alert/shake-alert.service.spec.ts
src/app/shake-alert/shake-alert.service.ts
src/app/shake-alert/shake-alert/shake-alert.component.spec.ts

Issue 1559

---

src/app/executive/pager-pin/pager-pin.component.html

replaced Econmic Fatalities with Fatalities

---

src/app/shared/css/summary-table.scss
src/app/shared/preferred-check/preferred-check.component.scss

fixes #1568 
This was just a small thing I noticed while reviewing the ticket.

Organize styles for preferred checkmark

---

src/app/ground-failure/alert-bar/alert-bar.component.html
src/app/ground-failure/alert-bar/alert-bar.component.scss
src/app/ground-failure/summary-view/summary-view.component.scss

added a bit of padding to the ground-failure histogram summary view

---

package-lock.json
src/app/product-page/header/header.component.html
src/app/product-page/header/header.component.spec.ts
src/app/product-page/header/header.component.ts
src/app/shared/product-property.pipe.ts
src/app/shared/product-reviewed.pipe.spec.ts
src/app/shared/product-reviewed.pipe.ts
src/app/shared/shared.module.ts

added shared product reviewed pipe

---

package-lock.json
src/app/dyfi/dyfi/dyfi.component.html
src/app/impact/impact/impact.component.html
src/app/pager/pager/pager.component.html
src/app/product-page/footer/footer.component.html
src/app/product-page/footer/footer.component.spec.ts
src/app/product-page/footer/footer.component.ts
src/app/product-page/product-page.module.ts
src/app/product-page/product-page/product-page.component.html
src/app/region-info/region-info-display/region-info-display.component.html
src/app/region-info/region-info-display/region-info-display.component.spec.ts
src/app/shakemap/shakemap/shakemap.component.html
src/app/shared/summary-link.pipe.spec.ts
src/app/shared/summary-link.pipe.ts
src/app/shared/summary-link/summary-link.component.html
src/app/technical/technical/technical.component.html
src/app/tell-us/tell-us/tell-us.component.html
src/app/tell-us/tell-us/tell-us.component.spec.ts
src/app/waveforms/waveforms/waveforms.component.html
src/app/waveforms/waveforms/waveforms.component.ts

Issue 1585

---

src/app/executive/executive/executive.component.html
src/app/executive/executive/executive.component.spec.ts
src/app/product-page/footer/footer.component.html
src/app/tell-us/tell-us/tell-us.component.html
src/app/waveforms/waveforms.module.ts
src/app/waveforms/waveforms/waveforms.component.html
src/app/waveforms/waveforms/waveforms.component.spec.ts

update summary links

---

package-lock.json
src/app/product-page/header/header.component.html
src/app/product-page/header/header.component.spec.ts

removed reviewed status from product header for scenario events

---

package-lock.json
src/app/event-page/event-page/event-page.component.html
src/app/event-page/navigation/navigation.component.html
src/app/event-page/navigation/navigation.component.spec.ts
src/app/shared/is-deleted-event.pipe.spec.ts
src/app/shared/is-deleted-event.pipe.ts
src/app/shared/shared.module.ts

Added isDeletedEvent pipe and hid sidenav for deleted events

---

src/app/executive/executive/executive.component.html
src/app/impact/impact/impact.component.html
src/app/technical/technical/technical.component.html

removed checks that caused some links to not show up for some events

---

src/app/product-page/download/download.component.spec.ts
src/app/product-page/download/download.component.ts

Update downloads section when product information changes

---

package-lock.json
src/app/shared/roman-to-number.pipe.spec.ts
src/app/shared/roman-to-number.pipe.ts
src/app/shared/shared.module.ts
src/app/tell-us/success-view/success-view.component.html
src/app/tell-us/success-view/success-view.component.spec.ts

added bubble to cdi value in success-view form

---

src/app/origin/magnitude/magnitude.component.html
src/app/origin/phase/phase.component.html

Display "no magnitudes" message on origin page

---

package-lock.json
src/app/shake-alert/shake-alert-confirmed/shake-alert-confirmed.component.html
src/app/shake-alert/shake-alert-confirmed/shake-alert-confirmed.component.spec.ts
src/app/shake-alert/shake-alert-confirmed/shake-alert-confirmed.component.ts
src/app/shake-alert/shake-alert-map/shake-alert-map.component.html
src/app/shake-alert/shake-alert-map/shake-alert-map.component.ts
src/app/shake-alert/shake-alert/shake-alert.component.html
src/app/shake-alert/shake-alert/shake-alert.component.spec.ts
src/app/tell-us/tell-us/tell-us.component.spec.ts

Issue 1604

---

src/app/shake-alert/shake-alert-confirmed/shake-alert-confirmed.component.html
src/app/shake-alert/shake-alert-confirmed/shake-alert-confirmed.component.scss
src/app/shake-alert/shake-alert-confirmed/shake-alert-confirmed.component.spec.ts
src/app/shake-alert/shake-alert-summary-report/shake-alert-summary-report.component.html
src/app/shake-alert/shake-alert-summary-report/shake-alert-summary-report.component.spec.ts
src/app/shake-alert/shake-alert-summary-report/shake-alert-summary-report.component.ts
src/app/shared/direction.pipe.spec.ts
src/app/shared/direction.pipe.ts
src/app/shared/number.pipe.ts
src/app/shared/shared.module.ts

Update shake-alert summary report

---

src/app/event-page/contributor-list.pipe.spec.ts
src/app/event.ts
src/app/shared/attribution/attribution.component.spec.ts
src/app/unique.ts

Change Event to check product sources for list of sources

---

package.json

fix missing shadow on material expansion panels
Please merge this,
https://github.com/usgs/hazdev-template/pull/312

Increment hazdev-ng-template version

---

src/app/tell-us/felt-report-reponse-error.ts
src/app/tell-us/felt-report-response-error-details.ts
src/app/tell-us/felt-report-response.ts
src/app/tell-us/felt-report-validation.ts
src/app/tell-us/felt-report.ts
src/app/tell-us/form/location/location.component.html
src/app/tell-us/form/location/location.component.ts
src/app/tell-us/form/location/map/map.component.ts
src/app/tell-us/location.ts

Issue-1631

---

src/app/tell-us/form/submit/submit.component.html

Issue-1627

---

src/app/tell-us/felt-report.ts
src/app/tell-us/form/abstract-form.component.ts
src/app/tell-us/form/location/location.component.html
src/app/tell-us/form/location/location.component.spec.ts
src/app/tell-us/form/location/location.component.ts
src/app/tell-us/form/location/map/map.component.spec.ts
src/app/tell-us/form/location/map/map.component.ts
src/app/tell-us/tell-us.module.ts

fixes #1626 
Also, if no location is entered and the map is expanded use the default location.

Update form to geocode users location

---

src/app/tell-us/tell-us/tell-us.component.html

Issue-1620

---

package-lock.json
package.json
src/app/tell-us/felt-report.ts
src/app/tell-us/form-language/tell-us-text.ts
src/app/tell-us/form/abstract-form.component.ts
src/app/tell-us/form/contact/contact.component.spec.ts
src/app/tell-us/form/felt/felt.component.spec.ts
src/app/tell-us/form/form.component.spec.ts
src/app/tell-us/form/form.component.ts
src/app/tell-us/form/location/location.component.html
src/app/tell-us/form/location/location.component.spec.ts
src/app/tell-us/form/location/location.component.ts
src/app/tell-us/form/location/map/map.component.spec.ts
src/app/tell-us/form/location/map/map.component.ts
src/app/tell-us/form/metadata/metadata.component.spec.ts
src/app/tell-us/form/metadata/metadata.component.ts
src/app/tell-us/form/optional/optional.component.spec.ts
src/app/tell-us/question/question.component.spec.ts
src/app/tell-us/response/response.component.spec.ts
src/app/tell-us/tell-us/tell-us.component.spec.ts

fixes #1623 
- This ticket includes updated tests.

Issue 1623

---

src/app/tell-us/form/form.component.html
src/app/tell-us/form/form.component.scss
src/app/tell-us/form/metadata/metadata.component.html
src/app/tell-us/form/metadata/metadata.component.scss

added OMB number above metadata

---

src/app/tell-us/felt-report.spec.ts
src/app/tell-us/form-language.service.ts

closes #1644 
... and remove unused code

Create tests for FeltReport

---

src/app/tell-us/success-view/success-view.component.spec.ts

closes #1647 
There wasn't much to do here, just cleaned it up a little and added one check.

SuccessViewComponent Tests

---

src/app/tell-us/form/contact/contact.component.ts
src/app/tell-us/form/felt/felt.component.ts
src/app/tell-us/form/metadata/metadata.component.spec.ts
src/app/tell-us/form/optional/optional.component.spec.ts
src/app/tell-us/form/optional/optional.component.ts
src/app/tell-us/form/questions.json

Clean up form components

---

src/app/tell-us/form/location/map/map.component.spec.ts
src/app/tell-us/form/location/map/map.component.ts

cleaned up code and updated test

---

src/app/tell-us/form-submit.service.spec.ts
src/app/tell-us/form-submit.service.ts
src/app/tell-us/form/form.component.html
src/app/tell-us/form/form.component.ts
src/app/tell-us/form/location/location.component.spec.ts
src/app/tell-us/form/location/map/map.component.ts
src/app/tell-us/form/submit/submit.component.html
src/app/tell-us/form/submit/submit.component.spec.ts
src/app/tell-us/form/submit/submit.component.ts
src/app/tell-us/response/response.component.html
src/app/tell-us/response/response.component.scss
src/app/tell-us/response/response.component.ts
src/app/tell-us/tell-us.module.ts
src/app/tell-us/tell-us/tell-us.component.html
src/app/tell-us/tell-us/tell-us.component.ts

refactored form submission

---

src/app/tell-us/form/abstract-form.component.ts
src/app/tell-us/form/form.component.spec.ts

fixed form tests and cleaned up abstract-form

---

src/app/tell-us/response/response.component.spec.ts

updated and added test

---

src/app/tell-us/form/submit/submit.component.spec.ts
src/app/tell-us/question/question.component.html
src/app/tell-us/question/question.component.spec.ts

Tests for questions and submit component

---

src/app/tell-us/form/location/location.component.html
src/app/tell-us/form/location/location.component.spec.ts
src/app/tell-us/form/location/location.component.ts

Issue 1650

---

src/app/tell-us/form-submit.service.spec.ts
src/app/tell-us/form-submit.service.ts

Test form-submit.service

---

src/app/tell-us/form/form.component.scss
src/app/tell-us/form/metadata/metadata.component.html
src/app/tell-us/form/metadata/metadata.component.scss

I thought some of the styles were messy, so I tried to clean up the left edge and make sure that form elements lined up. 
**Before**
---
**After**
---

Form layout changes

---

src/app/tell-us/form-submit.service.ts

dyfi form version number

---

src/app/tell-us/form/metadata/metadata.component.html

Remove PRA from header

---

src/app/dyfi/responses/responses.component.html
src/app/dyfi/responses/responses.component.scss

Fix scoping on shared-bubble style

---

src/app/event-page/contributor-list.pipe.ts
src/app/event-page/footer/footer.component.html

Issue 1707

---

src/app/product-page/download/download.component.spec.ts
src/app/product-page/download/download.component.ts

fixes #1717 
Fix issue where earthquake poster downloads were not appearing on the executive summary page

fix earthquake poster downloads

---

src/app/tell-us/form-submit.service.ts
src/app/tell-us/form/optional/optional.component.html

fixes #1721
I will push this code out as a hotfix, if merged it can be rolled into a proper tag.

DYFI Form Fix

---

package-lock.json
src/app/pager/pager/pager.component.html
src/app/pager/pagerxml.service.spec.ts
src/app/pager/pagerxml.service.ts

added data loading info box, If no pager data show warning box

---

proxy.conf.js
src/app/shared/geo.service.ts
src/app/tell-us/form-language/en.json
src/app/tell-us/form-submit.service.spec.ts
src/app/tell-us/form-submit.service.ts
src/app/tell-us/form/location/map/map.component.spec.ts
src/app/tell-us/form/location/map/map.component.ts
src/app/tell-us/form/questions.json

fixes #1721 
Once this gets merged we should verify with @vinceq-usgs that dyfi submissions are working as expected.

DYFI submission fix

---

src/app/shake-alert/shake-alert-summary-report/shake-alert-summary-report.component.html

removed ground motion accuracy section

---

proxy.conf.js
src/app/finite-fault/finite-fault/finite-fault.component.html

Add scientific background page for finite fault

---

src/app/tell-us/error-response/error-response.component.ts
src/app/tell-us/form-submit.service.ts
src/app/tell-us/response/response.component.spec.ts
src/app/tell-us/response/response.component.ts

Issue 1732

---

src/app/shake-alert/shake-alert-confirmed/shake-alert-confirmed.component.html
src/app/shake-alert/shake-alert-map/shake-alert-map.component.html
src/app/shake-alert/shake-alert-map/shake-alert-map.component.ts
src/app/shared/map-overlay/asynchronous-geojson-overlay.ts
src/app/shared/map-overlay/shake-alert-overlay.ts

fixes #1737 
Used on this event, requires some updating to summary.json:
http://localhost:4200/usp000hvnc/shake-alert
updated summary.json
[summary.json.txt](https://github.com/usgs/earthquake-eventpages/files/3016261/summary.json.txt)

Update initial and final alert maps to work with updated summary.json

---

src/app/shake-alert/shake-alert-map/shake-alert-map.component.html
src/app/shake-alert/shake-alert-map/shake-alert-map.component.scss

Update padding on shake-alert maps

---

src/app/shake-alert/shake-alert-confirmed/shake-alert-confirmed.component.html

Update ShakeAlert header

---

src/app/shared/map-overlay/shake-alert-overlay.spec.ts
src/app/shared/map-overlay/shake-alert-overlay.ts

Add epicenter marker to static maps on shake-alert page

---

src/app/shared/map-overlay/shake-alert-overlay.ts

Issue 1750

---

src/app/shake-alert/shake-alert-confirmed/shake-alert-confirmed.component.html
src/app/shake-alert/shake-alert-summary-report/shake-alert-summary-report.component.html
src/app/shared/date-time.pipe.spec.ts
src/app/shared/date-time.pipe.ts

Update time values on shake-alert

---

src/app/shared/map-overlay/shake-alert-overlay.spec.ts
src/app/shared/map-overlay/shake-alert-overlay.ts

Translate geojson css to leaflet styles

---

src/app/shake-alert/shake-alert-missed/shake-alert-missed.component.html
src/app/shake-alert/shake-alert-missed/shake-alert-missed.component.spec.ts
src/app/shake-alert/shake-alert-missed/shake-alert-missed.component.ts
src/app/shake-alert/shake-alert.service.spec.ts
src/app/shake-alert/shake-alert/shake-alert.component.html
src/app/shake-alert/shake-alert/shake-alert.component.spec.ts
src/app/shared/text-product/text-product.component.ts

Issue 1764

---

package.json
src/app/shared/ngx-charts/common/custom-legend/custom-legend.component.ts

Fixes broken bundle,
```
main.baf9cd1698bb41399604.js:1 ERROR Error: Uncaught (in promise): ReferenceError: NgxLegendComponent is not defined
ReferenceError: NgxLegendComponent is not defined
```

Broken build

---

src/app/executive/ground-failure-pin/ground-failure-pin.component.html

Change title in ground-failure pin

---

package-lock.json
src/app/shared/number-with-separator.pipe.spec.ts

link to es code
https://github.com/jdbrown-USGS/earthquake-eventpages/pull/new/brokenTest

Broken test

---

src/app/shake-alert/shake-alert-confirmed/shake-alert-confirmed.component.html
src/app/shared/number-with-separator.pipe.spec.ts

Add announcement property to shake-alert page

---

src/app/shake-alert/shake-alert-confirmed/shake-alert-confirmed.component.html
src/app/shake-alert/shake-alert-nearby-cities/shake-alert-nearby-cities.component.html
src/app/shake-alert/shake-alert-nearby-cities/shake-alert-nearby-cities.component.spec.ts
src/app/shake-alert/shake-alert-summary-report/shake-alert-summary-report.component.html
src/app/shake-alert/shake-alert-summary-report/shake-alert-summary-report.component.spec.ts
src/app/shared/distance.pipe.spec.ts
src/app/shared/distance.pipe.ts
src/app/shared/number-with-separator.pipe.spec.ts
src/app/shared/shared.module.ts

fixes #1791 
This will handle formatting distances into `XX km (YY mi)` for shake-alert

Create a sharedDistance pipe

---

package.json
src/app/shake-alert/shake-alert-confirmed/shake-alert-confirmed.component.html
src/app/shared/number-with-separator.pipe.spec.ts

Remove footnote #3

---

src/app/shared/css/leaflet-styles.scss

Fix the issue with the fixed position attribution on leaflet map.

---

src/app/executive/shake-alert-pin/shake-alert-pin.component.html

Update logo on shake-alert pin

---

src/app/shakemap/analysis/analysis.component.html
src/app/shakemap/plot-atten.pipe.ts
src/app/shakemap/plot-stations.pipe.ts
src/app/shared/css/mmi-colors.scss
src/app/shared/css/station-overlay.scss
src/app/shared/ngx-charts/bubble-line-chart/bubble-line-chart/bubble-line-chart.component.ts

closes #1814 
closes #1816
And fix mmi colors for stations missing intensity

Attenuation curves on residual plots

---

src/app/shared/css/station-overlay.scss
src/app/shared/map-overlay/shakemap-stations-overlay.ts

Resize station icons on map

---

src/app/unknown-event-page/unknown-event-page/unknown-event-page.component.html

similar to how it is configured on event page

Configure contact on unknown event page

---

src/app/shakemap/plot-stations.pipe.ts
src/app/shared/station/station.component.html

closes #1826 
closes #1835 
closes #1838

Various quick shakemap updates

---

src/app/ground-failure/alert-bar/alert-bar.component.html

Remove area estimate from groundfailure bar

---

package-lock.json
package.json
src/app/shared/get-map-bounds.pipe.spec.ts
src/app/shared/get-map-bounds.pipe.ts

@dslosky-usgs : fyi, not sure if the lon check was needed.  lat check definitely not.
Ground Failure for this event zooms to area that does not include epicenter, triggering lat check, and zooms to include south pole...
https://earthquake.usgs.gov/earthquakes/eventpage/us6000c9hg/ground-failure/summary

Weird zoom behavior
