usgs/earthquake-eventpages

src/htdocs/modules/base/EventModulePage.js
src/htdocs/modules/impact/ImpactSummaryPage.js
src/htdocs/modules/scientific/ScientificSummaryPage.js

Add getPreferredSummaryMarkup to EventModulePage, both ImpactSummaryPage and ScientificSummaryPage extend the EventModulePage. This will allow us to more easily override the getPreferredSummaryMarkup method in the event admin project.

LATESTEQ-330

---

src/htdocs/css/_event-header.scss
src/htdocs/modules/impact/PagerPage.js

This creates a border (inset box-shadow) on the pager pending impact bubble. It also adds this same border to all impact bubbles. This also helps with the super saturated colors like you see with the yellow alerts. This PR also decreases font-size inside the impact bubble to increase space.

Emartinez pager pending

---

src/htdocs/modules/summary/_TectonicSummary.scss

Fix css that displays thumbnails of tectonic summary posters
Example of problem:
http://earthquake.usgs.gov/earthquakes/eventpage/ak11639524#general_summary

Update styles for tectonic summary thumbnails

---

package.json
src/htdocs/modules/impact/ShakeMapPage.js

Add "alert" class to the error message and log the caught exception in the ajax request
depends on https://github.com/usgs/hazdev-webutils/pull/73
fixes https://github.com/usgs/earthquake-eventpages/issues/239

Improve error handling for station list data on shakemap page

---

src/htdocs/js/core/ContentView.js
src/htdocs/js/general/GeoserveNearbyPlacesView.js
src/htdocs/js/general/GeoserveRegionSummaryView.js
src/htdocs/js/general/NearbyPlacesView.js

Fixes #308 
At least deals with errors that were appearing on the console.  Other views used outside the general module should also abort active Xhr requests during destroy.
The errors appear to be caused by repeated hashchange events when triggering window.location changes within the code.  When the page is loaded at '#map', and the user clicks the Close Map button, onBack changes the location using `window.location = '#general'`.  When this triggers onHashChange window.location.hash is not up to date and again sets `window.location = '#general'`.  This leads to a double render where the general module is created, destroyed before renders are complete, and recreated.

General module 3

---

package.json

Depends on usgs/quakeml-parser-js#6
Fixes #458

Update event pages to use latest version of quakeml-parser-js

---

gruntconfig/connect.js

Fixes #482 
The default attribution url set by pre-install works with the updated proxy configuration.

Combine offsite_host proxy sections, add urls to be proxied

---

src/htdocs/js/core/SummaryModule.js
src/htdocs/js/moment-tensor/BeachBallView.js

Fix for focal-mechanism plotting bug reported by ghayes.
Page with bug (and screenshot); background colors are flipped from what is expected:
http://earthquake.usgs.gov/earthquakes/eventpage/usp0009qb4#focal-mechanism?source=us&code=pde20000328110022510_126_B_US
Page with expected plot (and screenshot); background colors are correct:
http://earthquake.usgs.gov/earthquakes/eventpage/usp0009qb4#focal-mechanism?source=us&code=choy20000328110022
Seems to be related to the first FM including a scalar moment, and the s2alphan parameter becoming greater than 1.  This addresses by checking if s2alphan is within epsilon of 1 before considering it greater than 1.

Focal mechanism plotting

---

src/htdocs/js/core/EventPage.js

This class name is used by the template to style the "up-on-level" link in the naviation

Add class name to Latest Earthquakes link in navigation

---

src/htdocs/js/dyfi/DYFIIntensityGraphView.js

This pull request relies on changes to hazdev-d3 to work.
usgs/hazdev-d3#17
fixes #509

Intensity vs. Distance plot doesn't show ticks for certain axis ranges.

---

src/htdocs/css/core/_BasicPinView.scss
src/htdocs/css/dyfi/_DYFIFormPinView.scss
src/htdocs/css/losspager/_PAGERPinView.scss
src/htdocs/css/moment-tensor/_MomentTensorPinView.scss
src/htdocs/css/origin/_OriginPinView.scss

These are changes that make the pins look more uniform across all the different content
fixes usgs/earthquake-eventpages#638

Css consistency

---

src/htdocs/js/moment-tensor/BeachBallView.js

Windows 8 IE 11 had occasional trouble plotting the non-double-couple portion of moment tensors.  Apparently `Number.EPSILON` is not defined.  This pull request tries to use Number.EPSILON, and falls back to a default epsilon value when it is not defined.
BeachBallView is the only file that uses Number.EPSILON in this project.
Example moment tensor:
http://earthquake.usgs.gov/earthquakes/eventpage/us200066x9#moment-tensor?source=us&code=us_200066x9_mww

Use constant for EPSILON when Number.EPSILON is not defined.

---

src/htdocs/js/dyfi/DYFIFormModule.js

This was duplicating the form markup when you show/hide the DYFI Tell Us! form
fixes #659 
Turns out the iOS issue was just connection issue where our mobile devices could not access the response page to post the form data.

Remove DYFIFormView.render from DYFIFormModule.showForm method

---

src/htdocs/js/dyfi/DYFIIntensityGraphView.js

When the log tick scale is not used, make sure numbers are whole numbers

---

src/app/executive/executive.module.ts
src/app/executive/executive/executive.component.css
src/app/executive/executive/executive.component.html
src/app/executive/executive/executive.component.scss
src/app/executive/executive/executive.component.spec.ts
src/app/executive/executive/executive.component.ts
src/app/executive/origin-pin/origin-pin.component.html
src/app/executive/origin-pin/origin-pin.component.scss
src/app/executive/origin-pin/origin-pin.component.spec.ts
src/app/executive/origin-pin/origin-pin.component.ts
src/app/formatter.service.ts
src/app/product-page/product-page.module.ts

fixes #756 
I changed the layout a bit. I moved the "contributed by" section to the top so that it is part of the mat-card "subtitle", I think this works better so that we can put our call-to-action at the bottom. The whole pin is still clickable, but this follows the material design layout.

Origin Pin Component

---

src/app/executive/executive/executive.component.html
src/app/executive/executive/executive.component.spec.ts
src/app/executive/origin-pin/origin-pin.component.html
src/app/executive/origin-pin/origin-pin.component.spec.ts
src/app/executive/origin-pin/origin-pin.component.ts
src/app/formatter.service.ts

fixes #756 
Completed:
- Change `app-origin-pin` selector to simply `origin-pin`.
- Be sure to capture `null` case for product properties and use `&ndash;` appropriately.
- Review Status
- Magnitude (and Type)
- Time
- Prefer `formatterService.dateTime` over built-in `date` pipe
- Probably use `formatterService` for other outputs (which captures `null` values already)
- Need tests for `ngOnChanges` method
Not Completed:
- Thoughts on an "attribution" component rather than a repeated design pattern?
- Maybe abstract out some of the common implementation (structure, styles, etc...) to a generic pin component ? Maybe this can be done as part of the next pin.
It seems like each part of the pin components is to unique to get much use out of an abstracted pin component. I think that an …

Origin Pin Fixes

---

src/app/event-page/event-page.module.ts
src/app/executive/basic-pin/basic-pin.component.html
src/app/executive/basic-pin/basic-pin.component.spec.ts
src/app/executive/basic-pin/basic-pin.component.ts
src/app/executive/executive.module.ts
src/app/executive/executive/executive.component.html
src/app/executive/executive/executive.component.spec.ts
src/app/executive/executive/executive.component.ts
src/app/executive/origin-pin/origin-pin.component.html
src/app/executive/origin-pin/origin-pin.component.spec.ts
src/app/executive/origin-pin/origin-pin.component.ts
src/app/executive/regional-pin/regional-pin.component.html
src/app/executive/regional-pin/regional-pin.component.spec.ts
src/app/executive/regional-pin/regional-pin.component.ts
src/environments/environment.ts

fixes #757 
**Addressed**
- Change class name to `region-info-pin`
- Change selector to `region-info-pin`
- Remove `console.log` statements
- Use sub-domains on tileLayer URL.
- Coding standards
- Use a space between function name and opening parens during function declaration/definition
- Prefer `L.marker` over `new L.Marker` (unless this doesn't work)
- Why was 'earthquake.usgs.gov' added back to environment config? Is this not fixed with `npm start` ?
- Probably should abstract out the pin view now that there are two we can see commonalities and room for code re-use.
- Headers strucuture / styles
- Attribution structure / styles
- Call to action structure / styles
**In Progress**
- Unit tests need more coverage (currently 66/35/85/64).
**Ignored**
- Pins should be same height/width
**I …

Update Region-Info pin

---

index.ts
src/app/core/metadata.service.spec.ts
src/app/core/metadata.service.ts
src/app/core/station.service.spec.ts
src/app/core/station.service.ts
src/app/shakemap/shakemap.module.ts

closes #826
Handles missing stationlist.json and info.json products
Converts string `"null"` and `"nan"` values in stationlist.json to `null`
Converts some non-array objects into arrays to match current info.json schema
Improved test coverage for station and metadata service

Improve handling of old shakemap products

---

src/app/shared/css/leaflet-styles.scss
src/app/shared/map/map.component.scss
src/app/shared/map/map.component.ts
src/styles.scss

fixes #879 
The attribution collapses to one line with ellipsis on overflow (when on smaller screens)

Update styles for leaflet controls

---

src/app/map/map/map.component.html
src/app/map/map/map.component.spec.ts
src/app/shared/interactive-map-bounds.pipe.spec.ts
src/app/shared/interactive-map-bounds.pipe.ts
src/app/shared/map/map.component.spec.ts
src/app/shared/map/map.component.ts
src/app/shared/shared.module.ts

- bounds parameter for embedded shared-map:
```
<shared-map
[bounds]="[[34, -118], [35, -117]]"
...
```
- bounds query param when linking to interactive map:
```
<a
[routerLink]="'../../map'"
[queryParams]="{
bounds: [
[34, -118],
[35, -117]
],
'ground-failure-landslide': true
}">
...
```

Support explicit map bounds

---

Jenkinsfile.groovy

The jobs archive only keeps logs, configurations, and specific artifacts for each build. It does not preserve the workspace itself. For debugging it may be necessary to keep a single copy of the workspace available after a build. For this reason, cleanup at start of next build instead.
This will keep one copy of the workspace on disk (~400 MB) but using `deleteDir` rather than `cleanWs` will prevent the duplicate workspace copies in the *cleanup* directories that were for some reason not getting deleted.

Using deleteDir rather than cleanWs. Space saver.

---

Jenkinsfile.groovy

Running container as root creates artifacts in workspace owned by root and jenkins can not delete using `deleteDir`. Root was not needed on build and this allows delete to work and build to pass.

Fix delete to work

---

src/app/event-page/navigation/navigation.component.html
src/app/executive/executive/executive.component.html
src/app/ground-failure/about/about.component.html
src/app/ground-failure/ground-failure/ground-failure.component.html

fixes #951 
- Change the position of the ground-failure pin. The pin should come after PAGER. 
- Remove TODO from "ShakeMap" & "Impact" on side navigation
- Update "ground failure background" link on the about tab, it should link to `/data/ground-failure/background.php`

wrap up issues from sprint

---

src/app/shakemap/intensity/intensity.component.html
src/app/shakemap/intensity/intensity.component.spec.ts
src/app/shakemap/pga/pga.component.html
src/app/shakemap/pga/pga.component.spec.ts
src/app/shakemap/pgv/pgv.component.html
src/app/shakemap/pgv/pgv.component.spec.ts
src/app/shakemap/psa/psa.component.html
src/app/shakemap/psa/psa.component.spec.ts
src/app/shared/css/contour-overlay.scss
src/app/shared/css/leaflet-styles.scss
src/app/shared/css/station-overlay.scss
src/app/shared/map-overlay/asynchronous-geojson-overlay.ts
src/app/shared/map-overlay/shakemap-contours-overlay.spec.ts
src/app/shared/map-overlay/shakemap-contours-overlay.ts
src/app/shared/map-overlay/shakemap-pga-overlay.spec.ts
src/app/shared/map-overlay/shakemap-pga-overlay.ts
src/app/shared/map-overlay/shakemap-pgv-overlay.spec.ts
src/app/shared/map-overlay/shakemap-pgv-overlay.ts
src/app/shared/map-overlay/shakemap-psa03-overlay.spec.ts
src/app/shared/map-overlay/shakemap-psa03-overlay.ts
src/app/shared/map-overlay/shakemap-psa10-overlay.spec.ts
src/app/shared/map-overlay/shakemap-psa10-overlay.ts
src/app/shared/map-overlay/shakemap-psa30-overlay.spec.ts
src/app/shared/map-overlay/shakemap-psa30-overlay.ts
src/app/shared/shakemap-overlays.pipe.ts
src/styles.scss

fixes #977  
- Using divIcon labels that looks similar to old static images
- Labeling every other contour to avoid clutter
- Labeling random spot on contour to avoid label collisions (still happens)
- subclassed for PGA/PGV/PSA overlays.

Contour overlays update

---

src/app/oaf/commentary/commentary.component.ts

Fix commentary tab to not modify the shared forecast for its own purpose.
This is a quick fix but we may need larger refactoring.

Patch Forecast Rendering

---

src/app/pager/pager/pager.component.html
src/app/pager/pager/pager.component.scss
src/app/pager/pager/pager.component.spec.ts
src/app/pager/pagerxml.service.spec.ts
src/app/pager/pagerxml.service.ts

In response to @jmfee-usgs and his comments on https://github.com/usgs/earthquake-eventpages/pull/973
```
remove the # link around exposure.png; this will eventually link to the interactive map, but not ready to yet and takes you to the unknown event form
```
Done.
```
add alt text to images
```
Done.
```
does the productSubscription need to move to ngAfterViewInit? it seems like ngOnInit would also work...
```
No it doesn't need to be in ngAfterViewInit. putting the subscription works fine in ngOnInit as long as you check the product type. Pretend that you are navigating from the origin module to the pager module. When the productSubscription is created in ngOnInit, the subscription returns an origin product when the subscription is set up. By adding the subscription to the …

Issue 898 fixes

---

docker-entrypoint.sh

Fixes #1232
To verify ...
- Pull in PR changes
- Build image
```
$ docker build -t local/earthquake-eventpages:latest .
```
- Start container
```
$ docker run --name test-eventpages --rm -p 8080:80 -e BASE_HREF=earthquakes/eventpage local/earthquake-eventpages:latest
```
- Load event page http://localhost:8080/earthquakes/eventpage/ci38245496/executive
- Inspect network tab / headers.
**Verify**
- All resources served from cache (so long as caching not disabled by browser and not hard refreshed). 
- Should have header: "Cache-Control" "public"
- Should have header: "Cache-Control" "max-age=900"
- Most resources should indicate "served from memory cache" or "served from disk cache"

Issue-1232

---

src/app/shared/date-time.pipe.ts

Closes #1272 
Stopped pre-parsing input dates and let the Date object take care of it. This will fail for string epoch dates (which we aren't ever passing it as far as I can tell), but gets the correct dates for ShakeMap and OAF data formats which appear to be the only modules using this pipe

Fixed metadata date issue

---

src/app/shared/date-time.pipe.spec.ts
src/app/shared/date-time.pipe.ts

closes #1272 
Added tests to ensure milliseconds since epoch and string timestamps can be read and transformed correctly. Also testing some graceful handling of non-supported input types

Additional tests and doc string for sharedDateTime pipe

---

src/app/dyfi/responses-vs-time/responses-vs-time.component.ts

closes #1262 
Switching to between minutes/hours using the `preferred_unit` property generated by DYFI. Switched back to linear scale for the x-axis

Responses vs. time x-scale

---

src/app/product-page/download-item/download-item.component.html
src/app/product-page/download-item/download-item.component.spec.ts
src/app/product-page/file-extension.pipe.spec.ts
src/app/product-page/file-extension.pipe.ts
src/app/product-page/product-page.module.ts

@ghayes-usgs pointed out that we were showing mime types instead of file extensions, different from the production pages.  I agree that file extensions are less cryptic than mime-types for most users.

Show file extensions in download view, instead of mime-types

---

src/app/executive/executive/executive.component.html
src/app/executive/finite-fault-pin/finite-fault-pin.component.html
src/app/finite-fault/finite-fault/finite-fault.component.html

fixes #1321 
Updated Finite fault pin logic and logic in the finite-fault.component. The fall backs where not working correctly because of the sharedProductProperties pipe. Appending to them caused a null value to return. After spending quite some time on this problem I was unable to find a solution. Perhaps creating a new pipe to handle the formatting better? I don't see this being a problem anywhere else other than finite fault and the backups should be going away in the long term? Also the reason for creating the sharedProductProperties pipe in the first place is not an issue here as the elvis operator can be used.

Issue 1321

---

package.json

fixes #1323 
Update geoserve output to fix tectonic summary images

Increment hazdev-ng-geoserve-output dependency

---

src/app/shakemap/psa/psa.component.html
src/app/shakemap/psa/psa.component.spec.ts
src/app/shared/map-overlay/shakemap-contours-overlay.spec.ts
src/app/shared/map-overlay/shakemap-contours-overlay.ts

closes #1199 
closes #1315
Using Shakemap v4 products in PSA tab
Using weight and color properties when available, added intensity legend, and added popup content for PGA/PGV/PSA contours

Shakemap overlays update

---

src/app/dyfi/dyfi.service.ts
src/app/dyfi/intensity-vs-distance/intensity-vs-distance.component.html
src/app/dyfi/intensity-vs-distance/intensity-vs-distance.component.spec.ts
src/app/dyfi/intensity-vs-distance/intensity-vs-distance.component.ts
src/app/shared/ngx-charts/bubble-chart/bubble-series/bubble-series.component.ts
src/app/shared/ngx-charts/bubble-line-chart/bubble-line-chart/bubble-line-chart.component.html
src/app/shared/ngx-charts/bubble-line-chart/bubble-line-chart/bubble-line-chart.component.ts

closes #1197 
Added number of responses to the popup tooltip when available
Scaling transparency with nresp when available
Plotting the IPE lines above the user entry points
It's a little hard to test... but the sample data is [here](https://github.com/usgs/earthquake-eventpages/files/2425318/dyfi_plot_atten.json.txt). Copy and paste that in place of the `response` in the dyfiService's getPlotAtten function [here](https://github.com/usgs/earthquake-eventpages/blob/e0d609fec0634be42d17100b2ebfe7b4040dd200/src/app/dyfi/dyfi.service.ts#L38) to see the new tooltips and scaling

DYFI Intensity Vs. Distance plot update

---

src/app/shakemap/metadata/processing/processing.component.html
src/app/shakemap/metadata/processing/processing.component.ts
src/app/shared/units.pipe.spec.ts
src/app/shared/units.pipe.ts

closes #1387 
Hide ROI when the data isn't present
Stop rounding degrees by default in the sharedUnits pipe
Add version history (new in Shakemap v4)

Shakemap metadata update

---

src/app/shakemap/intensity/intensity.component.html
src/app/shakemap/intensity/intensity.component.spec.ts
src/app/shakemap/pga/pga.component.html
src/app/shakemap/pga/pga.component.spec.ts
src/app/shakemap/pgv/pgv.component.html
src/app/shakemap/pgv/pgv.component.spec.ts
src/app/shakemap/psa/psa.component.html
src/app/shakemap/psa/psa.component.spec.ts
src/app/shared/map-overlay/shakemap-contours-overlay.spec.ts
src/app/shared/map-overlay/shakemap-contours-overlay.ts
src/app/shared/map/map.component.ts

closes #1128 
Use max/min lat/lon from Shakemap product to set map bounds
Switched to default basemap for all static maps
Set zoomSnap to 0 to allow precise setting of bounds

Shakemap bounds and basemaps

---

src/app/origin/magnitude-detail/magnitude-detail.component.scss
src/app/origin/phase/phase.component.scss
src/app/pager/pager/pager.component.scss
src/app/shared/css/description-table.scss
src/styles.scss

fixes #1244 
Add space so that column values do not smush together, and stop values from wrapping onto multiple lines

Column spacing on mat-tables

---

src/app/executive/executive/executive.component.html
src/app/executive/map-pin/map-pin.component.ts
src/app/shared/beachball/beachball.ts
src/app/shared/beachball/canvas.ts
src/app/shared/beachball/matrix.ts
src/app/shared/beachball/tensor.ts
src/app/shared/beachball/vector.ts

Removed extra parameter in nearbySeismicityLink pipe usage
Added correct `Event` definition to the map-pin
Had to add `// @dynamic` to the classes exported in the beachball component... for some reason...

AOT compilation errors fixed

---

src/app/executive/shakemap-pin/shakemap-pin.component.html
src/app/shared/mmi/mmi.component.scss
src/app/shared/roman.pipe.spec.ts
src/app/shared/roman.pipe.ts

closes #1467 
If the value passed into the pipe is not a number or present in the roman numeral lookup, return 'N/A'

Return N/A from sharedRoman

---

src/app/shared/css/station-overlay.scss

closes #1504 
Makes stations transparent/gray when they're missing an MMI

Add styles for no-mmi stations in station-overlay

---

src/app/shakemap/shakemap/shakemap.component.scss

fixes #1578
Set static width to max width in order to avoid shakemap overflow on mobile

Map overflow bug

---

src/app/shared/dyfi-summary/dyfi-summary.component.html
src/app/shared/dyfi-summary/dyfi-summary.component.spec.ts
src/app/shared/dyfi-summary/dyfi-summary.component.ts
src/app/shared/finite-fault-summary/finite-fault-summary.component.html
src/app/shared/finite-fault-summary/finite-fault-summary.component.ts
src/app/shared/focal-mechanism-summary/focal-mechanism-summary.component.html
src/app/shared/focal-mechanism-summary/focal-mechanism-summary.component.spec.ts
src/app/shared/focal-mechanism-summary/focal-mechanism-summary.component.ts
src/app/shared/origin-summary/origin-summary.component.html
src/app/shared/origin-summary/origin-summary.component.ts
src/app/shared/pager-summary/pager-summary.component.html
src/app/shared/pager-summary/pager-summary.component.spec.ts
src/app/shared/pager-summary/pager-summary.component.ts
src/app/shared/shakemap-summary/shakemap-summary.component.html
src/app/shared/shakemap-summary/shakemap-summary.component.spec.ts
src/app/shared/shakemap-summary/shakemap-summary.component.ts

fixes #1593 
Ensure that the summary components link to the correct pages from the impact/technical summary pages, and that tab position is maintained when switching between contributed versions on the product page

Switching between versions in summary component

---

src/app/shared/geo.service.ts
src/app/tell-us/form/location/location.component.spec.ts
src/app/tell-us/form/location/location.component.ts

I decided to subscribe to the service in the `location.component` because that is where the user triggers a geocode or geolocate. If we were to have the `geo.service` show the MatSnackBar then it would have to be referenced in multiple places. It felt much easier to have the MatSnackBar accept a `LocationError` object and display the `LocationError.message` in the MatSnackBar.

Display LocationError in SnackBar

---

src/app/tell-us/form/location/map/map.component.scss
src/app/tell-us/form/location/map/map.component.spec.ts
src/app/tell-us/form/location/map/map.component.ts

closes #1694 
This also includes a small style change to remove the bottom-padding from the map on larger screens. Without this style the map overflows its 960x960 px parent container

change map bounds from 4 degrees to 2 degrees

---

src/app/tell-us/form/submit/submit.component.html
src/app/tell-us/form/submit/submit.component.scss
src/app/tell-us/form/submit/submit.component.spec.ts
src/app/tell-us/form/submit/submit.component.ts

fixes #1695 
This feels like a very simple solution. I started to go down the route of linking to the form inputs, however this would require refactoring the form. I am not sure if you can create an `ElementRef` unless the element is in the same component, so I believe we would have to flatten the structure of the form to provide focus to the actual form input when clicking on the link.

Add simple scroll link from form errors to the top of the page

---

src/app/shake-alert/shake-alert-confirmed/shake-alert-confirmed.component.html
src/app/shake-alert/shake-alert-confirmed/shake-alert-confirmed.component.scss
src/app/shake-alert/shake-alert-confirmed/shake-alert-confirmed.component.ts
src/app/shared/date-time.pipe.spec.ts
src/app/shared/map-overlay/shake-alert-overlay.spec.ts
src/app/shared/map-overlay/shake-alert-overlay.ts

fixes #1752 
You can use event `nc73143141` to see the labels displayed on the map

Add tooltips to shake-alert-overlay

---

src/app/shared/interactive-map-overlays.pipe.ts
src/app/unique.spec.ts
src/app/unique.ts

Fixes #1768 , by choosing the origin EpicenterOverlay (which is first and preferred) over the shakemap EpicenterOverlay.
This may be all that is needed, although it changes the behavior of getUnique().  This appears to be the only place getUnique() is used with objects.

Fix event plotting discrepency on executive summary page

---

src/app/shared/ground-failure-overlays.pipe.ts

Incomplete ground-failure products currently break interactive map pin.

Wrap ground-failure-overlays in case contents are missing

---

Jenkinsfile.groovy

pointed TEST_IMAGE to use usgs/ng-cli-e2e (our new trion image)

updated jenkinsfile to use our new trion image
